name: 'Create File Update PR'
description: 'Pushes a new branch with changed files and opens a PR for updating the changed files in the base branch'
inputs:
  no-hash: # turn off inclusion of the hash in the created branch name
    description: 'Do not include the changed file hash in the PR branch name'
    default: false
  replace-branch: # if a PR branch already exists, replaces it with updated contents
    description: 'Replace the contents of an existing PR branch of the same name'
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
