/*
Copyright (c) 2019-2025,
Lawrence Livermore National Security, LLC;
See the top-level NOTICE for additional details. All rights reserved.
SPDX-License-Identifier: BSD-3-Clause
*/
#include "units.hpp"

#include <algorithm>
#include <array>
#include <cstring>
#include <string>
#include <tuple>

namespace UNITS_NAMESPACE {

namespace precise {
    using unitD = std::tuple<const char*, const char*, precise_unit>;
    static UNITS_CPP14_CONSTEXPR_OBJECT std::array<unitD, 812> x12_units{{
        unitD{"03", "SECOND", precise::s},
        unitD{"05", "LIFT", {1.0, count, commodities::packaging::lift}},
        unitD{"07", "STRAND", {1.0, count, commodities::packaging::strand}},
        unitD{"09", "TIRE", {1.0, count, commodities::tires}},
        unitD{"10", "GROUP", {1.0, count, commodities::packaging::group}},
        unitD{"11", "OUTFIT", {1.0, count, commodities::packaging::outfit}},
        unitD{"12", "PACKET", {1.0, count, commodities::packaging::packet}},
        unitD{"13", "RATION", {1.0, count, commodities::packaging::ration}},
        unitD{"14", "SHOT", precise::us::shot},
        unitD{"15", "STICK", {1.0, count, commodities::packaging::stick}},
        unitD{
            "17",
            "100 POUND DRUM",
            {100.0, lb, commodities::packaging::drum}},
        unitD{
            "18",
            "55 GALLON DRUM",
            {55.0, us::gallon, commodities::packaging::drum}},
        unitD{
            "19",
            "TANK TRUCK",
            {1.0, count, commodities::packaging::tanktruck}},
        unitD{"1A", "CAR MILE", {1.0, mile, commodities::packaging::car}},
        unitD{"1B", "CAR COUNT", {1.0, count, commodities::packaging::car}},
        unitD{
            "1C",
            "locomotive count",
            {1.0, count, commodities::packaging::locomotive}},
        unitD{
            "1D",
            "CABOOSE COUNT",
            {1.0, count, commodities::packaging::caboose}},
        unitD{"1E", "CAR COUNT", {1.0, count, commodities::packaging::car}},
        unitD{"1F", "train mile", {1.0, mile, commodities::packaging::train}},
        unitD{"1G", "GALLON", us::gallon},
        unitD{
            "1H",
            "CABOOSE MILE",
            {1.0, mile, commodities::packaging::caboose}},
        unitD{
            "1I",
            "FIXED RATE",
            {1.0, count, commodities::packaging::fixed_rate}},
        unitD{"1J", "ton mile", ton* mile},
        unitD{
            "1K",
            "locomotive mile",
            {1.0, mile, commodities::packaging::locomotive}},
        unitD{
            "1L",
            "total car count",
            {1.0, count, commodities::packaging::car}},
        unitD{"1M", "total car mile", {1.0, mile, commodities::packaging::car}},
        unitD{"1N", "COUNT", count},
        unitD{"1O", "SEASON", {0.25, yr}},
        unitD{"1P", "TANK CAR", {1.0, count, commodities::packaging::tankcar}},
        unitD{"1Q", "FRAME", {1.0, count, commodities::frame}},
        unitD{"1R", "TRANSACTION", {1.0, count, commodities::transactions}},
        unitD{"1X", "quarter mile", {0.25, mile}},
        unitD{"20", "twenty foot container", {20.0 * 8.0 * 8.5, ft.pow(3)}},
        unitD{"21", "forty foot container", {40.0 * 8.0 * 8.5, ft.pow(3)}},
        unitD{"22", "DECILITER PER GRAM", deci* L / g},
        unitD{"23", "Grams per Cubic Centimeter", g / cm.pow(3)},
        unitD{
            "24",
            "THEORETICAL POUND",
            {1.0, lb, commodities::packaging::theoretical}},
        unitD{"25", "Grams per Square Centimeter", g / cm.pow(2)},
        unitD{"26", "ACTUAL TONS", {1.0, ton, commodities::packaging::actual}},
        unitD{
            "27",
            "THEORETICAL TON",
            {1.0, ton, commodities::packaging::theoretical}},
        unitD{"28", "kilogram per square metre", kg / m.pow(2)},

        unitD{
            "29",
            "pound per thousand square foot",
            lb / (thousand * ft.pow(2))},
        unitD{"2A", "radian per second", rad / s},
        unitD{"2B", "radian per second squared", rad / s.pow(2)},
        unitD{"2C", "roentgen", cgs::roentgen},
        unitD{"2D", "SHIP SET", {1.0, count, commodities::packaging::shipset}},
        unitD{"2F", "volt per metre", V / m},
        unitD{"2G", "volt_ac", V},
        unitD{"2H", "volt_dc", V},
        unitD{
            "2I",
            "BRITISH THERMAL UNITS/HOUR",
            precise::energy::btu_it / precise::hr},
        unitD{"2J", "CUBIC CENTIMETER PER SECOND", cm.pow(3) / s},
        unitD{"2K", "CUBIC FEET PER HOUR", ft.pow(3) / hr},
        unitD{"2L", "CUBIC FEET PER MINUTE", ft.pow(3) / minute},
        unitD{"2M", "CENTIMETER PER SECOND", cm / s},
        unitD{"2N", "DECIBEL", log::dB},
        unitD{"2P", "kilobyte", data::kB},
        unitD{"2Q", "kilobecquerel", kilo* Bq},
        unitD{"2R", "KILOCURIE", kilo* cgs::curie},
        unitD{"2U", "MEGAGRAM", precise::mega* precise::g},
        unitD{"2V", "MEGAGRAM PER HOUR", mega* g / hr},
        unitD{"2W", "BIN", {1.0, count, commodities::packaging::bin}},
        unitD{"2X", "METRE PER MINUTE", m / minute},
        unitD{"2Y", "milliroentgen", milli* cgs::roentgen},
        unitD{"2Z", "millivolt", milli* V},
        unitD{
            "30",
            "HORSEPOWER DAYS PER AIR DRY METRIC TONS",
            hp* day / precise_unit(t, commodities::packaging::dry)},
        unitD{"31", "POUND UNIT", pu* lb},
        unitD{
            "32",
            "kilogram per air dry metric ton",
            kg / precise_unit(t, commodities::packaging::dry)},
        unitD{
            "33",
            "kilopascal square metre per gram",
            kilo * Pa * m.pow(2) / g},
        unitD{"34", "kilopascal per millimetre", kilo* Pa / mm},
        unitD{
            "35",
            "millilitre per square centimetre second",
            mL / (cm.pow(2) * s)},
        unitD{
            "36",
            "Cubic Feet per Minute per Square Foot",
            ft.pow(3) / minute / ft.pow(2)},
        unitD{"37", "ounce per square foot", oz / ft.pow(2)},
        unitD{
            "38",
            "ounce per square foot per 0.01inch",
            oz / ft.pow(2) / precise_unit(0.01, in)},
        unitD{"39", "basis points", {0.1, precise::milli}},
        unitD{"3B", "MEGAJOULE", mega* J},
        unitD{"3C", "MANMONTH", {1.0, time::mog, commodities::people}},
        unitD{"3E", "pound per pound of product", pu* lb},
        unitD{"3F", "kilogram per litre of Product", kg / L},
        unitD{"3G", "pound per piece of product", lb / count},
        unitD{"3H", "kilogram per kilogram of product", pu* kg},
        unitD{"40", "millilitre per second", mL / s},
        unitD{"41", "MILLILITRE PER MINUTE", mL / minute},
        unitD{
            "43",
            "SUPER BULK BAG (SAME SIZE AS PALLET)",
            {1.0, count, commodities::packaging::bulk_bag}},
        unitD{
            "44",
            "500 KILOGRAM BULK BAG",
            {500.0, kg, commodities::packaging::bulk_bag}},
        unitD{
            "45",
            "300 KILOGRAM BULK BAG",
            {300.0, kg, commodities::packaging::bulk_bag}},
        unitD{
            "46",
            "25 KILOGRAM BULK BAG",
            {25.0, kg, commodities::packaging::bulk_bag}},
        unitD{"47", "50 POUND BAG", {50.0, lb, commodities::packaging::bag}},
        unitD{
            "48",
            "BULK CAR LOAD",
            {1.0, count, commodities::packaging::bulk_car}},
        unitD{"4A", "BOBBIN", {1.0, count, commodities::packaging::bobbin}},
        unitD{"4B", "CAP", {1.0, count, commodities::packaging::cap}},
        unitD{"4C", "CENTISTOKE", cgs::stokes* centi},
        unitD{"4D", "CURIE", cgs::curie},
        unitD{"4E", "20-PACK", precise_unit(20, precise::count)},
        unitD{"4F", "100-PACK", precise_unit(100, precise::count)},
        unitD{"4G", "MICROLITER", precise::micro* precise::L},
        unitD{"4I", "METERS PER SECOND", precise::m / precise::s},
        unitD{"4J", "METERS PER SECOND PER SECOND", m / s.pow(2)},
        unitD{"4K", "milliampere", milli* A},
        unitD{"4L", "MEGABYTE", data::MB},
        unitD{"4M", "milligram per hour", mg / hr},
        unitD{"4N", "MEGABECQUEREL", mega* becquerel},
        unitD{"4O", "microfarad", micro* F},
        unitD{"4P", "newton per metre", N / m},
        unitD{"4Q", "ounce inch", oz* in},
        unitD{"4R", "ounce foot", oz* ft},
        unitD{"4S", "PASCAL", Pa},
        unitD{"4T", "picofarad", pico* F},
        unitD{"4U", "pound per hour", lb / hr},
        unitD{"4V", "CUBIC METER PER HOUR", m.pow(3) / hr},
        unitD{"4W", "ton (US) per hour", ton / hr},
        unitD{"4X", "kilolitre per hour", kilo* L / hr},
        unitD{
            "50",
            "ACTUAL KILOGRAMS",
            {1.0, kg, commodities::packaging::actual}},
        unitD{
            "51",
            "ACTUAL TONNES",
            {1.0, ton, commodities::packaging::actual}},
        unitD{"52", "credits", {1.0, currency, commodities::credits}},
        unitD{
            "53",
            "THEORETICAL KILOGRAM",
            {1.0, kg, commodities::packaging::theoretical}},
        unitD{
            "54",
            "THEORETICAL TONNE",
            {1.0, mass::tonne, commodities::packaging::theoretical}},
        unitD{"56", "sitas", {100.0, m.pow(2)}},
        unitD{"57", "MESH", precise::clinical::mesh},
        unitD{
            "58",
            "NET KILOGRAMS",
            {1.0, kg, commodities::packaging::net_quantity}},
        unitD{"59", "part per million", other::ppm},
        unitD{"5A", "BARREL PER MINUTE", us::barrel / minute},
        unitD{"5B", "BATCH", {1.0, count, commodities::packaging::batch}},
        unitD{"5C", "GALLON PER 1000", us::gallon / (kilo * count)},
        unitD{
            "5D",
            "PROOF GALLONS",
            {1.0,
             gal,
             commodities::package(
                 commodities::packaging::equivalent,
                 commodities::chemicals::alcohol)}},
        unitD{
            "5E",
            "MILLION CUBIC FEET PER DAY",
            precise::mega* precise::energy::scf / day},
        unitD{"5F", "pound per thousand", lb / (kilo * count)},
        unitD{"5G", "PUMP", {1.0, count, commodities::packaging::pump}},
        unitD{"5H", "STAGE", {1.0, count, commodities::packaging::stage}},
        unitD{"5I", "STANDARD CUBE FOOT", ft.pow(3)},
        unitD{"5J", "hydraulic horse power", power::hpS},

        unitD{"5K", "ITEMS PER MINUTE", count / minute},
        unitD{"5P", "seismic level", special::moment_magnitude},
        unitD{"5Q", "seismic line", special::moment_energy},
        unitD{"60", "percent weight", percent * pu * kg},
        unitD{"61", "part per billion", other::ppb},
        unitD{"62", "percent per 1000 hour", percent / (thousand * hr)},
        unitD{
            "63",
            "FAILURES PER SECOND",
            {1.0, count / s, commodities::failure}},
        unitD{"64", "pound per square inch, gauge", lbf / in.pow(2)},
        unitD{"65", "COULOMB", C},
        unitD{"66", "oersted", cgs::oersted},
        unitD{"67", "SIEMENS", S},
        unitD{"68", "AMPERE", A},
        unitD{"69", "TEST SPECIFIC SCALE", generate_custom_unit(333)},
        unitD{"70", "VOLT", precise::volt},
        unitD{"71", "volt ampere per pound", V* A / lb},
        unitD{"72", "watt per pound", W / lb},
        unitD{
            "73",
            "AMPERE-TURN PER CENTIMETER",
            precise::A* precise::count / cm},
        unitD{"74", "millipascal", milli* Pa},
        unitD{"76", "GAUSS", cgs::gauss},
        unitD{"77", "mil", milli* inch},
        unitD{"78", "kilogauss", kilo* cgs::gauss},
        unitD{"79", "electronvolt", energy::eV},
        unitD{"7A", "LANDINGS", count},
        unitD{"7C", "FLIGHT HOURS", h},
        unitD{"80", "pound per square inch absolute", lb / in.pow(2)},
        unitD{"81", "HENRY", henry},
        unitD{"82", "OHM", ohm},
        unitD{"83", "FARAD", F},
        unitD{"84", "kilopound-force per square inch", kilo* lbf / in.pow(2)},
        unitD{"85", "FOOT-POUND", ft* lbf},
        unitD{"86", "JOULES", J},
        unitD{"87", "pound per cubic foot", lb / ft.pow(3)},
        unitD{"89", "poise", cgs::poise},
        unitD{"8C", "CORD", precise::us::cord},
        unitD{"8D", "DUTY", {1.0, count, commodities::duty}},
        unitD{"8P", "PROJECT", {1.0, count, commodities::project}},
        unitD{"8R", "PROGRAM", {1.0, count, commodities::program}},
        unitD{"8S", "SESSION", {1.0, count, commodities::session}},
        unitD{"8U", "SQUARE KILOMETER", precise::km.pow(2)},
        unitD{"90", "Saybold universal second", {0.2158, mm.pow(2) / s}},
        unitD{"91", "STOKE", precise::cgs::stokes},
        unitD{"92", "CALORIE PER CUBIC CENTIMETER", cal / cm.pow(3)},
        unitD{"93", "CALORIE PER GRAM", cal / g},
        unitD{"94", "CURL UNIT", generate_custom_unit(335)},

        unitD{
            "95",
            "20,000 GALLON TANKCAR",
            {20000.0, us::gallon, commodities::packaging::tankcar}},
        unitD{
            "96",
            "10,000 GALLON TANKCAR",
            {10000.0, us::gallon, commodities::packaging::tankcar}},
        unitD{"97", "ten kg drum", {10.0, kg, commodities::packaging::drum}},
        unitD{
            "98",
            "15 KILOGRAM DRUM",
            {15.0, kg, commodities::packaging::drum}},
        unitD{"99", "WATT", precise::watt},
        unitD{"9A", "APOTHECARY POUND", precise::apothecaries::pound},
        unitD{"9B", "BRIQUET", {1.0, count, commodities::packaging::briquet}},
        unitD{"9F", "FOLD", {1.0, count, commodities::fold}},
        unitD{"9O", "APOTHECARY OUNCE", precise::apothecaries::ounce},
        unitD{"9P", "PILLOW", {1.0, count, commodities::pillow}},
        unitD{"9S", "SEAT", {1.0, count, commodities::seat}},
        unitD{"9Y", "FAMILY UNIT", precise::one},
        // defined from ucom definition USP'U which generate a custom unit
        unitD{
            "9Z",
            "united states pharmacopoeia unit",
            precise::generate_custom_unit(43)},
        unitD{"A8", "dollar per hour", currency / hr},
        unitD{"AA", "BALL", {1.0, count, commodities::packaging::ball}},
        unitD{
            "AB",
            "BULK PACK",
            {1.0, count, commodities::packaging::bulk_pack}},
        unitD{"AC", "ACRE", acre},
        unitD{"AD", "BYTE", precise::B},
        unitD{"AE", "AMPERE PER METER", A / m},
        unitD{"AF", "CENTIGRAM", centi* g},
        unitD{"AG", "ANGSTROM", distance::angstrom},
        unitD{"AH", "MINUTE", minute},
        unitD{
            "AI",
            "MINUTES PER CALL",
            minute / precise_unit(one, commodities::call)},
        unitD{
            "AJ",
            "COP (CYLINDRICAL OR CONICAL MASS)",
            {1.0, count, commodities::packaging::cop}},
        unitD{"AK", "FATHOM", nautical::fathom},
        unitD{"AL", "ACCESS LINES", {1.0, count, commodities::linesofservice}},
        unitD{"AM", "AMPOULE", {1.0, count, commodities::packaging::ampoule}},
        unitD{"AN", "minutes or messages", {1.0, count, commodities::message}},
        unitD{"AO", "Ampere-turn", A* count},
        unitD{"AP", "aluminium pound only", {1.0, lb, commodities::aluminum}},
        unitD{"AQ", "AHF UNITS", clinical::AHF},
        unitD{
            "AR",
            "SUPPOSITORY",
            {1.0, count, commodities::packaging::suppository}},
        unitD{
            "AS",
            "ASSORTMENT",
            {1.0, count, commodities::packaging::assortment}},
        unitD{"AT", "ATMOSPHERE", pressure::atm},
        unitD{
            "AU",
            "ocular insert system",
            {1.0, count, commodities::packaging::ocular_insert_system}},
        unitD{"AV", "CAPSULE", {1.0, count, commodities::packaging::capsule}},
        unitD{
            "AW",
            "POWDER-FILLED VIAL",
            {1.0, count, commodities::packaging::powder_vial}},
        unitD{"AX", "TWENTY", {20.0, count}},
        unitD{"AY", "ASSEMBLY", {1.0, count, commodities::packaging::assembly}},
        unitD{"AZ", "BTU PER POUND", energy::btu_it / lb},
        unitD{
            "B0",
            "BRITISH THERMAL UNITS PER CUBIC FOOT",
            precise::btu / (precise::ft.pow(3))},
        unitD{"B1", "barrel (US) per day", us::barrel / day},
        unitD{"B2", "BUNK", {1.0, count, commodities::packaging::bunk}},
        unitD{"B3", "BATTING POUND", {1.0, lb, commodities::fiber}},
        unitD{"B4", "BARREL IMPERIAL", imp::winebarrel},
        unitD{"B5", "BILLET", {1.0, count, commodities::packaging::billet}},
        unitD{"B6", "BUN", milli* mol / L},
        unitD{"B7", "CYCLE", {constants::tau, rad}},
        unitD{"B8", "BOARD", {1.0, count, commodities::packaging::board}},
        unitD{"B9", "BATT", {1.0, count, commodities::packaging::batt}},
        unitD{"BA", "BALE", {1.0, count, commodities::packaging::bale}},
        unitD{"BB", "BASS BOX", {1.0, count, commodities::packaging::base_box}},
        unitD{"BC", "BUCKET", {1.0, count, commodities::packaging::bucket}},
        unitD{"BD", "BUNDLE", {1.0, count, commodities::packaging::bundle}},
        unitD{"BE", "BEAM", {1.0, count, commodities::packaging::beam}},
        unitD{"BF", "BOARD FOOT", i::board_foot},
        unitD{"BG", "BAG", {1.0, count, commodities::packaging::bag}},
        unitD{"BH", "BRUSH", {1.0, count, commodities::packaging::brush}},
        unitD{"BI", "BAR", {1.0, count, commodities::packaging::bar}},
        unitD{"BJ", "BAND", {1.0, count, commodities::packaging::band}},
        unitD{"BK", "BOOK", {1.0, count, commodities::packaging::book}},
        unitD{"BL", "BLOCK", {1.0, count, commodities::packaging::block}},
        unitD{"BM", "BOLT", {1.0, count, commodities::packaging::bolt}},
        unitD{"BN", "BULK", precise_unit(count, commodities::packaging::bulk)},
        unitD{"BO", "BOTTLE", {1.0, count, commodities::packaging::bottle}},
        unitD{"BP", "100 BOARD FEET", hundred* i::board_foot},
        unitD{"BQ", "brake horse power", power::hpM},
        unitD{"BR", "BARREL", precise::us::barrel},
        unitD{"BS", "BASKET", {1.0, count, commodities::packaging::basket}},
        unitD{"BT", "BELT", {1.0, count, commodities::packaging::belt}},
        unitD{"BU", "BUSHEL", us::dry::bushel},
        unitD{"BV", "BUSHEL DRY IMPERIAL", imp::bushel},
        unitD{"BW", "BASE WEIGHT", kg},
        unitD{"BX", "BOX", {1.0, count, commodities::packaging::box}},
        unitD{"BY", "British thermal unit", energy::btu_it},
        unitD{"BZ", "MILLION BTUS", mega* btu},
        unitD{"C0", "CALLS", {1.0, count, commodities::call}},
        unitD{
            "C1",
            "COMPOSITE PRODUCT POUNDS (TOTAL WEIGHT)",
            {1.0, lb, commodities::packaging::composite}},
        unitD{"C2", "CARSET", {1.0, count, commodities::packaging::carset}},
        unitD{"C3", "centilitre", centi* L},
        unitD{"C4", "CARLOAD", {1.0, count, commodities::packaging::car}},
        unitD{"C5", "COST", {1.0, currency, commodities::packaging::actual}},
        unitD{"C6", "CELL", {1.0, count, commodities::packaging::cell}},
        unitD{"C7", "centipoise", centi* cgs::poise},
        unitD{"C8", "CUBIC DECIMETER", (deci * m).pow(3)},
        unitD{
            "C9",
            "COIL GROUP",
            {1.0, count, commodities::packaging::coil_group}},
        unitD{"CA", "CASE", {1.0, count, commodities::packaging::small_case}},
        unitD{"CB", "CARBOY", {1.0, count, commodities::packaging::carboy}},
        unitD{"CC", "CUBIC CENTIMETER", precise::cm.pow(3)},
        unitD{"CD", "CARAT", metric::carat},
        unitD{"CE", "degree Celsius", degC},
        unitD{"CF", "CUBIC FOOT", precise::ft.pow(3)},
        unitD{"CG", "CARD", {1.0, count, commodities::packaging::card}},
        unitD{
            "CH",
            "CONTAINER",
            {1.0, count, commodities::packaging::container}},
        unitD{"CI", "CUBIC INCH", precise::in.pow(3)},
        unitD{"CJ", "CONE", {1.0, count, commodities::packaging::cone}},
        unitD{
            "CK",
            "CONNECTOR",
            {1.0, count, commodities::packaging::connector}},
        unitD{"CL", "CYLINDER", {1.0, count, commodities::packaging::cylinder}},
        unitD{"CM", "CENTIMETER", precise::cm},
        unitD{"CN", "CAN", {1.0, count, commodities::packaging::can}},
        unitD{"CO", "cubic metre (net)", m.pow(3)},
        unitD{"CP", "CRATE", {1.0, count, commodities::packaging::crate}},
        unitD{
            "CQ",
            "CARTRIDGE",
            {1.0, count, commodities::packaging::cartridge}},
        unitD{"CR", "CUBIC METER", precise::m.pow(3)},
        unitD{"CS", "CASSETTE", {1.0, count, commodities::packaging::cassette}},
        unitD{"CT", "CARTON", {1.0, count, commodities::packaging::carton}},
        unitD{"CU", "CUP", us::cup},
        unitD{"CV", "COVER", {1.0, count, commodities::packaging::cover}},
        unitD{"CW", "HUNDRED POUNDS", precise_unit(100.0, precise::lb)},
        unitD{"CX", "COIL", {1.0, count, commodities::packaging::coil}},
        unitD{"CY", "CUBIC YARD", precise::yd.pow(3)},
        unitD{"CZ", "COMBO", {1.0, count, commodities::packaging::combo}},
        unitD{"D1", "INVERSE SECOND PER RADIAN SQUARED", s.inv() / rad.pow(2)},
        unitD{
            "D2",
            "INVERSE SECOND PER RADIAN SQUARED PER METER SQUARED",
            s.inv() / (rad.pow(2) * m.pow(2))},
        unitD{"D3", "square decimetre", (deci * m).pow(2)},
        unitD{"D5", "kilogram per square centimetre", kg / cm.pow(2)},
        unitD{"D8", "CUSTOM UNIT 341", generate_custom_unit(341)},
        unitD{"D9", "DYNE PER SQUARE CENTIMETER", cgs::dyn / cm.pow(2)},
        unitD{"DA", "DAY", precise::time::day},
        unitD{"DB", "dry pound", {1.0, lb, commodities::packaging::dry}},
        unitD{"DC", "disk (disc)", {1.0, count, commodities::packaging::disk}},
        unitD{"DD", "DEGREE", deg},
        unitD{"DE", "deal", {1.0, count, commodities::packaging::deal}},
        unitD{"DF", "dram (US)", apothecaries::drachm},
        unitD{"DG", "DECIGRAM", precise_unit(0.1, g)},
        unitD{"DH", "MILE", precise::mile},
        unitD{
            "DI",
            "DISPENSER",
            {1.0, count, commodities::packaging::dispenser}},
        unitD{"DJ", "DECAGRAM", precise_unit(10.0, g)},
        unitD{"DK", "KILOMETER", precise::km},
        unitD{"DL", "DECILITER", deci* L},
        unitD{"DM", "DECIMETER", deci* m},
        unitD{"DN", "DECIMETER-NEWTON", deci * N * m},
        unitD{
            "DO",
            "DOLLARS U.S.",
            {1.0, currency, commodities::currencies::dollar}},
        unitD{"DP", "DOZEN PAIR", precise_unit(24.0, count)},
        unitD{"DQ", "DATA RECORD", {1.0, count, commodities::record}},
        unitD{"DR", "DRUM", {1.0, count, commodities::packaging::drum}},
        unitD{"DS", "DISPLAY", {1.0, count, commodities::packaging::display}},
        unitD{"DT", "DRY TON", {1.0, ton, commodities::packaging::dry}},
        unitD{"DU", "DYNE", precise::cgs::dyn},
        unitD{"DV", "DEGREES, KELVIN", precise::K},
        unitD{"DW", "CALENDAR DAYS (NUMBER OF)", precise::time::day},
        unitD{"DX", "dyne per centimetre", cgs::dyn / cm},
        unitD{
            "DY",
            "DIRECTORY BOOKS",
            {1.0, count, commodities::packaging::book}},
        unitD{"DZ", "DOZEN", precise_unit(12, count)},
        unitD{"E1", "HECTOMETER", precise_unit(100, precise::m)},

        unitD{"E3", "trailer", {1.0, ton, commodities::packaging::trailer}},
        unitD{
            "E4",
            "gross kilogram",
            {1.0, kg, commodities::packaging::gross_quantity}},
        unitD{"E5", "metric long ton", av::longton},
        unitD{
            "E7",
            "inches decimal-average",
            {1.0, in, commodities::packaging::average}},
        unitD{
            "E8",
            "inches decimal-actual",
            {1.0, in, commodities::packaging::actual}},
        unitD{"E9", "english feet and inches", {1.0, imp::foot}},
        unitD{"EA", "EACH", precise::count},
        unitD{
            "EB",
            "ELECTRONIC MAIL BOXES",
            {1.0, count, commodities::electronic_mail_box}},
        unitD{"EC", "each per month", count / time::moj},
        unitD{
            "ED",
            "inches decimal-nominal",
            {1.0, in, commodities::packaging::nominal}},
        unitD{"EE", "EMPLOYEES", {1.0, count, commodities::employee}},
        unitD{
            "EF",
            "inches fraction-nominal",
            {1.0, in, commodities::packaging::nominal}},
        unitD{"EG", "double time hours", {1.0, hr, commodities::doubletime}},
        unitD{"EH", "KNOTS", precise::nautical::knot},
        unitD{"EJ", "LOCATIONS", {1.0, count, commodities::locations}},
        unitD{
            "EM",
            "inches decimal-minimum",
            {1.0, in, commodities::packaging::minimum}},
        unitD{"EP", "ELEVEN PACK", {11, precise::count}},
        unitD{
            "EQ",
            "EQUIVALENT GALLONS",
            {1.0, gal, commodities::packaging::equivalent}},
        unitD{
            "EV",
            "ENVELOPES",
            {1.0, count, commodities::packaging::envelope}},
        unitD{"EX", "Feet Inches and fraction", ft},
        unitD{"EY", "Feet inches and Decimal", ft},
        unitD{"EZ", "Feet and Decimal", ft},
        unitD{"F1", "thousand cubic foot per day", {1000.0, ft.pow(3) / day}},
        unitD{"F2", "INTERNATIONAL UNIT", precise::laboratory::IU},
        unitD{
            "F3",
            "equivalent",
            {1.0, precise::one, commodities::packaging::equivalent}},
        unitD{"F4", "MINIM", precise::us::minim},
        unitD{"F5", "molar mass", g / mol},
        unitD{
            "F6",
            "PRICE PER SHARE",
            currency /
                precise_unit(
                    1.0,
                    count,
                    commodities::generateShareCode("     "))},
        unitD{
            "F9",
            "FIBERS PER MILLILITER",
            precise_unit(count, commodities::fiber) /
                precise_unit(cm.pow(3), commodities::air)},
        unitD{"FA", "FAHRENHEIT", degF},
        unitD{"FB", "FIELDS", {1.0, count, commodities::packaging::field}},
        unitD{"FC", "1000 CUBIC FEET", precise::kilo* precise::ft.pow(3)},
        unitD{
            "FD",
            "million particle per cubic foot",
            precise_unit{
                mega * count / ft.pow(3),
                commodities::packaging::particle}},
        unitD{"FE", "TRACK FOOT", {1.0, ft, commodities::packaging::track}},
        unitD{
            "FF",
            "HUNDRED CUBIC METERS",
            precise_unit(100.0, precise::m.pow(3))},
        unitD{
            "FG",
            "TRANSDERMAL PATCH",
            {1.0, count, commodities::packaging::patch}},
        unitD{"FH", "micromole", micro* mol},
        unitD{"FJ", "SIZING FACTOR", ratio},
        unitD{"FK", "FIBER", {1.0, count, commodities::fiber}},
        unitD{"FL", "FLAKE TON", {1.0, ton, commodities::packaging::flake}},
        unitD{"FM", "MILLION CUBIC FEET", precise::mega* precise::ft.pow(3)},
        unitD{"FO", "FLUID OUNCE", precise::us::floz},
        unitD{"FP", "pound per square foot", lb / ft.pow(2)},
        unitD{"FR", "foot per minute", ft / minute},
        unitD{"FS", "FEET PER SECOND", ft / s},
        unitD{"FT", "FOOT", precise::ft},
        unitD{"FU", "FURLONG", us::furlong},
        unitD{"FZ", "fluid ounce (UK)", imp::floz},

        unitD{"G2", "GALLONS PER MINUTE", us::gallon / minute},
        unitD{"G3", "Imperial gallon per minute", imp::gallon / minute},

        unitD{"G4", "gigabecquerel", giga* Bq},
        unitD{"G5", "GILL (IMPERIAL)", imp::gill},
        unitD{"G6", "bit", data::bit},
        unitD{
            "G7",
            "microfiche sheet",
            {1.0, count, commodities::packaging::sheet}},
        unitD{"G8", "GigaCalories", giga* energy::cal_th},
        unitD{"G9", "gigabyte", giga* data::byte},
        unitD{"GA", "GALLON", us::gallon},
        unitD{"GB", "gallon (US) per day", us::gallon / day},

        unitD{"GC", "PERCENT", g / (hecto * g)},
        unitD{
            "GD",
            "ITEMS PER BARREL",
            {144.0, count, commodities::packaging::barrel}},
        unitD{"GE", "pound per gallon (US)", lb / us::gallon},
        unitD{"GF", "GRAMS PER METER", g / m},
        unitD{"GG", "GREAT GROSS", {1728.0, count}},
        unitD{"GH", "HALF GALLON", {0.5, us::gallon}},
        unitD{"GI", "IMPERIAL GALLON", imp::gallon},
        unitD{"GJ", "GRAM PER MILLILITER", g / mL},
        unitD{"GK", "GRAM PER KILOGRAM", g / kg},
        unitD{"GL", "gram per litre", g / L},
        unitD{"GM", "gram per square metre", g / m.pow(2)},
        unitD{"GN", "gross gallon", {144.0, gal}},
        unitD{"GO", "milligram per square metre", mg / m.pow(2)},
        unitD{"GP", "milligram per cubic metre", mg / m.pow(3)},
        unitD{"GQ", "microgram per cubic metre", micro* g / m.pow(3)},
        unitD{"GR", "GRAM", precise::g},
        unitD{"GS", "GROSS", {144.0, count}},
        unitD{
            "GT",
            "Gross kilogram",
            {1.0, kg, commodities::packaging::gross_quantity}},
        unitD{"GU", "gauss per oersteds", cgs::gauss / cgs::oersted},
        unitD{"GV", "GIGAJOULE", giga* J},
        unitD{
            "GW",
            "GALLONS PER THOUSAND CUBIC FEET",
            us::gallon / (kilo * ft.pow(3))},
        unitD{"GX", "GRAIN", i::grain},
        unitD{"GY", "YARD", yd},
        unitD{"GZ", "GRAYVALUE", eflag},
        unitD{
            "H1",
            "HALF ITEM",
            {0.5, count, commodities::packaging::page_electronic}},
        unitD{"H2", "HALF LITER", half* L},
        unitD{"H4", "HECTOLITER", hecto* L},
        unitD{"HA", "HANK", {1.0, count, commodities::packaging::hank}},
        unitD{
            "HB",
            "HUNDRED BOXES",
            {100.0, count, commodities::packaging::box}},
        unitD{"HC", "HUNDRED COUNT", hundred* count},
        unitD{"HD", "HALF DOZEN", {6.0, count}},
        unitD{"HE", "hundredth of a carat", centi* metric::carat},

        unitD{"HF", "HUNDRED FEET", hundred* foot},
        unitD{"HG", "HECTOGRAM", hecto* g},
        unitD{
            "HH",
            "HUNDRED CUBIC FEET",
            precise_unit(100.0, precise::ft.pow(3))},
        unitD{
            "HI",
            "HUNDRED SHEETS",
            {100.0, count, commodities::packaging::sheet}},
        unitD{"HJ", "HORSEPOWER METRIC", precise::power::hpM},
        unitD{"HK", "HUNDRED KILOGRAM", hundred* kg},
        unitD{
            "HL",
            "HUNDRED FOOT (LINEAR)",
            {100.0, ft, commodities::packaging::linear}},
        unitD{"HM", "mile per hour", mph},
        unitD{"HN", "conventional millimetre of mercury", pressure::mmHg},
        unitD{"HO", "HUNDRED TROY OUNCES", hundred* troy::oz},
        unitD{"HP", "conventional millimetre of water", pressure::mmH2O},
        unitD{"HQ", "HECTARE", area::hectare},
        unitD{"HR", "HOUR", precise::hr},
        unitD{
            "HS",
            "HUNDRED SQUARE FEET",
            precise_unit(100.0, precise::ft.pow(2))},
        unitD{"HT", "HALF HOUR", half* hr},
        unitD{"HU", "HUNDRED", hundred* count},
        unitD{
            "HV",
            "HUNDRED WEIGHT - SHORT (HUNDRED WEIGHT)",
            av::hundredweight},
        unitD{"HW", "HUNDRED WEIGHT (LONG)", av::longhundredweight},
        unitD{"HX", "HOSPITAL BEDS", precise::one},
        unitD{"HY", "HUNDRED YARDS", hundred* yd},
        unitD{"HZ", "HERTZ", Hz},

        unitD{"I2", "PELLET", precise::one},
        unitD{"IA", "inch pound", in* lb},
        unitD{"IB", "inches per second (vibration velocity)", in / s},
        unitD{"IC", "ITEMS PER INCH", count / in},
        unitD{"IE", "PERSON", {1.0, count, commodities::person}},
        unitD{"IF", "inches of water", pressure::inH2O},
        unitD{"IG", "inner package", precise::one},
        unitD{"IH", "INHALER", precise::one},
        unitD{"II", "INCHES OF WATER", pressure::inH2O* eflag},
        unitD{"IK", "peaks per inch", {1.0, count / in, commodities::peak}},
        unitD{"IL", "INCHES PER MINUTE", in / minute},
        unitD{"IM", "IMPRESSION", {1.0, count, commodities::impression}},
        unitD{"IN", "INCH", precise::in},
        unitD{"IP", "INSURANCE POLICY", {1.0, count, commodities::policy}},
        unitD{"IS", "STOP", {1.0, count, commodities::stops}},
        unitD{"IT", "ITEMS PER CENTIMETER", count / cm},
        unitD{"IU", "inch per second", in / s},

        unitD{"IV", "INCHES PER SECOND SQUARED", in / s.pow(2)},
        unitD{
            "IW",
            "INCHES PER SECOND SQUARED (vibration acceleration)",
            in / s.pow(2)},
        unitD{"J2", "joule per kilogram", J / kg},

        unitD{"JA", "JOB", {1.0, count, commodities::job}},
        unitD{"JB", "JUMBO", {1.0, count, commodities::packaging::jumbo}},
        unitD{"JE", "JOULE PER KELVIN", J / K},
        unitD{"JG", "Joule per Gram", J / g},

        unitD{"JK", "MEGAJOULE PER KILOGRAM", mega* J / kg},
        unitD{"JM", "MEGAJOULE PER CUBIC METRE", mega* J / m.pow(3)},
        unitD{"JO", "JOINT", {1.0, count, commodities::packaging::joint}},
        unitD{"JR", "JAR", {1.0, count, commodities::packaging::jar}},
        unitD{"JU", "JUG", {1.0, count, commodities::packaging::jug}},
        unitD{"K1", "KILOWATT", electrical::kW},
        unitD{"K2", "kilovolt ampere reactive demand", electrical::kVAR},
        unitD{"K3", "KILOVOLT-AMPERE-REACTIVE-HOUR", electrical::kVAR* hr},
        unitD{"K4", "kilovolt - ampere", kilo * V * A},
        unitD{"K5", "KILOVOLT-AMPERE-REACTIVE", kilo* electrical::VAR},
        unitD{"K6", "KILOLITER", kilo* L},
        unitD{"K7", "KILOWATT", precise::electrical::kW},
        unitD{"K8", "KILOVOLT", precise::electrical::kV},
        unitD{"K9", "kilogram per millimeter squared", kg / mm.pow(2)},
        unitD{"KA", "CAKE", {1.0, count, commodities::packaging::cake}},
        unitD{"KB", "KILOBYTE", {1.0, kilo* count, commodities::character}},
        unitD{"KC", "kilogram per cubic meter", kg / m.pow(3)},
        unitD{"KD", "KILOGRAM", kg},
        unitD{"KE", "KEG", {1.0, count, commodities::packaging::keg}},
        unitD{"KF", "KILOPACKET", {1000.0, count, commodities::packet}},
        unitD{"KG", "KILOGRAM", precise::kg},
        unitD{"KH", "KILOWATT-HOUR", precise::kWh},
        unitD{"KI", "KILOGRAM PER MILLIMETER", kg / mm},
        unitD{
            "KJ",
            "THOUSAND ITEMS",
            {1.0, kilo* count, commodities::packaging::segment}},
        unitD{"KK", "100 KILOGRAMS", precise_unit(100.0, precise::kg)},
        unitD{"KL", "KILOGRAM PER METER", kg / m},
        unitD{"KM", "kilogram per square meter", kg / m.pow(2)},
        unitD{
            "KO",
            "THOUSAND PER GRAM",
            {1.0,
             milli / g,
             commodities::package(
                 commodities::packaging::equivalent,
                 commodities::chemicals::KOH)}},
        unitD{"KP", "kilometre per hour", km / hr},
        unitD{"KQ", "KILOPASCAL", kilo* Pa},
        unitD{"KR", "kiloroentgen", kilo* cgs::roentgen},
        unitD{"KS", "THOUSAND PSI", thousand* lb / in.pow(2)},
        unitD{"KT", "KIT", {1.0, count, commodities::packaging::kit}},
        unitD{"KU", "TASK", {1.0, count, commodities::task}},
        unitD{"KV", "KELVIN", precise::K},
        unitD{"KW", "KILOGRAM PER MILLIMETER", kg / mm},
        unitD{"KX", "MILLILITERS PER KILOGRAM", mL / kg},
        unitD{"L2", "litre per minute", L / minute},
        unitD{"L5", "LITERS AT 15 DEGREES CELSIUS", precise::one},
        unitD{"LA", "POUND PER CUBIC INCH", lb / in.pow(3)},
        unitD{"LB", "POUND (AVOIRDUPOIS)", lb},
        unitD{
            "LC",
            "CENTIMETER LINEAR",
            {1.0, cm, commodities::packaging::linear}},
        unitD{"LD", "LITER PER DAY", L / day},
        unitD{"LE", "LITE", {1.0, count, commodities::packaging::lite}},
        unitD{"LF", "LINEAR FOOT", {1.0, ft, commodities::packaging::linear}},
        unitD{"LG", "LONG TON", av::longton},
        unitD{"LH", "LABOR HOUR", {1.0, hr, commodities::labor}},
        unitD{"LI", "LINEAR INCH", {1.0, in, commodities::packaging::linear}},
        unitD{
            "LJ",
            "LARGE SPRAY",
            {1.0, count, commodities::packaging::large_spray}},
        unitD{"LK", "LINK", {1.0, count, commodities::packaging::length}},
        unitD{"LL", "lifetime", {70.0, time::year}},
        unitD{"LM", "LINEAR METER", {1.0, m, commodities::packaging::linear}},
        unitD{"LN", "LENGTH", {1.0, count, commodities::packaging::length}},
        unitD{"LO", "LOT", {1.0, count, commodities::packaging::lot}},
        unitD{"LP", "liquid pound", {1.0, lb, commodities::packaging::liquid}},
        unitD{"LQ", "liters per day", L / day},
        unitD{"LR", "LAYER", {1.0, count, commodities::packaging::layer}},
        unitD{"LS", "LUMP SUM", {1.0, currency, commodities::packaging::lump}},
        unitD{"LT", "LITER", L},
        unitD{
            "LX",
            "YARD LINEAR PER POUND",
            precise_unit(1.0, yd, commodities::packaging::linear) / lb},
        unitD{"LY", "LINEAR YARD", {1.0, yd, commodities::packaging::linear}},
        unitD{
            "M0",
            "MAGNETIC TAPE",
            {1.0,
             count,
             commodities::generateHarmonizedCode(85, 23, 29, 15, false)}},
        unitD{"M1", "MILLIGRAM PER LITER", mg / L},
        unitD{
            "M2",
            "millimeter-Actual",
            {1.0, mm, commodities::packaging::actual}},
        unitD{"M3", "MAT", {1.0, count, commodities::packaging::mat}},
        unitD{"M4", "CURRENCY", currency},
        unitD{"M5", "microcurie", micro* cgs::curie},
        unitD{"M6", "millibar", milli* bar},
        unitD{"M7", "MICROINCH", micro* in},
        unitD{"M8", "MEGAPASCAL", mega* Pa},
        unitD{
            "M9",
            "MILLION BTU PER THOUSAND CUBIC FEET",
            mega* btu / (thousand * ft.pow(3))},
        unitD{"MA", "machine per unit", {1.0, pu* count, commodities::machine}},
        unitD{
            "MB",
            "millimeter-nominal",
            {1.0, mm, commodities::packaging::nominal}},
        unitD{"MC", "MICROGRAM", micro* g},
        unitD{
            "MD",
            "AIR DRY METRIC TON",
            precise_unit(mass::tonne, commodities::packaging::dry)},
        unitD{"ME", "MILLIGRAM", precise::mg},
        unitD{
            "MF",
            "milligram per square foot per side",
            {1.0,
             mg / ft.pow(2) / precise_unit(one, commodities::packaging::side)}},
        unitD{"MG", "METRIC GROSS TON", precise::one},
        unitD{"MH", "micrometre", micro* m},
        unitD{"MI", "METRIC", {1.0, count, commodities::metric}},

        unitD{"MJ", "MINUTE", precise::minute},
        unitD{"MK", "milligram per square inch", mg / in.pow(2)},
        unitD{"ML", "MILLILITER", precise::milli* precise::L},
        unitD{"MM", "MILLIMETER", mm},
        unitD{
            "MN",
            "METRIC NET TON",
            {1.0, mass::tonne, commodities::packaging::net_quantity}},
        unitD{"MO", "MONTH", time::moj},
        unitD{"MP", "METRIC TON", mass::tonne},
        unitD{"MQ", "1000 METERS", thousand* m},
        unitD{"MR", "METER", precise::m},
        unitD{"MS", "SQUARE MILLIMETER", precise::mm.pow(2)},
        unitD{"MT", "METRIC LONG TON", mass::tonne},
        unitD{"MU", "millicurie", milli* cgs::curie},
        unitD{"MV", "ITEMS", count},
        unitD{"MW", "metric ton kilograms", tonne},
        unitD{"MX", "MIXED", {1.0, count, commodities::packaging::mixed}},
        unitD{
            "MY",
            "millimeter-average",
            {1.0, mm, commodities::packaging::average}},
        unitD{
            "MZ",
            "millimeter-minimum",
            {1.0, mm, commodities::packaging::minimum}},
        unitD{"N1", "pen calorie", cal},
        unitD{
            "N2",
            "NUMBER OF LINES",
            {1.0, count, commodities::linesofservice}},
        unitD{"N3", "print point", typographic::printers::point},
        unitD{"N4", "pen grams (protein)", {1.0, g, commodities::protein}},
        unitD{"N6", "MEGAHERTZ", mega* Hz},
        unitD{"N7", "PART", {1.0, count, commodities::packaging::parts}},
        unitD{
            "N9",
            "CARTRIDGE NEEDLE",
            {1.0, count, commodities::cartridge_needle}},
        unitD{"NA", "milligram per kilogram", mg / kg},
        unitD{"NB", "BARGE", {1.0, count, commodities::packaging::barge}},
        unitD{"NC", "CAR", {1.0, count, commodities::packaging::car}},
        unitD{
            "ND",
            "NET BARRELS",
            {1.0, us::barrel, commodities::packaging::net_quantity}},
        unitD{"NE", "NET LITERS", {1.0, L, commodities::packaging::net}},
        unitD{"NF", "MESSAGES", {1.0, count, commodities::message}},
        unitD{"NG", "NET GALLONS", {1.0, gal, commodities::packaging::net}},
        unitD{"NH", "MESSAGE HOUR", {1.0, hr, commodities::message}},
        unitD{
            "NI",
            "NET IMPERIAL GALLONS",
            {1.0, imp::gallon, commodities::packaging::net}},
        unitD{"NJ", "NUMBER OF SCREENS", {1.0, count, commodities::screen}},
        unitD{"NK", "NIGHTS", {1.0, count, commodities::night}},
        unitD{"NL", "LOAD", {1.0, count, commodities::packaging::load}},
        unitD{"NM", "NAUTICAL MILE", nautical::mile},
        unitD{"NN", "TRAIN", {1.0, count, commodities::packaging::train}},
        unitD{"NQ", "mho", ohm.inv()},
        unitD{"NR", "micromho", micro* ohm.inv()},
        unitD{"NS", "SHORT TON", av::ton},
        unitD{"NT", "TRAILER", {1.0, ton, commodities::packaging::trailer}},
        unitD{"NU", "newton metre", N* m},
        unitD{"NV", "VEHICLE", {1.0, count, commodities::vehicle}},
        unitD{"NW", "newton", N},
        unitD{"NX", "PARTS PER THOUSAND", milli* count},
        unitD{
            "NY",
            "pound per air dry metric ton",
            lb / precise_unit(mass::tonne, commodities::packaging::dry)},
        unitD{"NZ", "THOUSAND GALLONS PER DAY", {1000.0, gal / day}},
        unitD{"OA", "PANEL", {1.0, count, commodities::packaging::panel}},
        unitD{"OB", "OUTLET", precise::one},
        unitD{"OC", "BILLBOARD", {1.0, count, commodities::billboard}},
        unitD{
            "OG",
            "APOTHECARY GRAIN",
            precise_unit(1.0 / 5760.0, precise::apothecaries::pound)},
        unitD{"ON", "ounce per square yard", oz / yd.pow(2)},
        unitD{"OP", "TWO PACK", {2, count}},
        unitD{"OT", "overtime hour", {1.0, count, commodities::overtime}},
        unitD{"OU", "OPERATING UNIT", precise::one},
        unitD{"OZ", "AV OUNCE", av::ounce},
        unitD{
            "P0",
            "PAGE - ELECTRONIC",
            {1.0, count, commodities::packaging::page_electronic}},
        unitD{"P1", "PERCENT", percent},
        unitD{"P2", "POUNDS PER FOOT", lb / ft},
        unitD{"P3", "THREE PACK", {3, count}},
        unitD{"P4", "FOUR PACK", {4, count}},
        unitD{"P5", "FIVE PACK", {5, count}},
        unitD{"P6", "SIX PACK", {6, count}},
        unitD{"P7", "SEVEN PACK", {7, count}},
        unitD{"P8", "EIGHT PACK", {8, count}},
        unitD{"P9", "NINE PACK", {9, count}},
        unitD{"PA", "PAIL", {1.0, count, commodities::packaging::pail}},
        unitD{"PB", "PAIR INCHES", {2, count* in}},
        unitD{"PC", "PIECE", count},
        unitD{"PD", "PAD", {1.0, count, commodities::packaging::pad}},
        unitD{
            "PE",
            "POUNDS EQUIVALENT",
            {10.0, lb, commodities::packaging::equivalent}},
        unitD{
            "PF",
            "PALLET (LIFT)",
            {1.0, count, commodities::packaging::pallet}},
        unitD{"PG", "POUNDS GROSS", lb},
        unitD{"PH", "PACK (PAK)", {1.0, count, commodities::packaging::pack}},
        unitD{"PI", "PITCH", {1.0, count / in, commodities::character}},
        unitD{
            "PJ",
            "pounds, Decimal - Pounds per square foot - Pound gage",
            pressure::psig},
        unitD{"PK", "PACKAGE", {1.0, count, commodities::packaging::pack}},
        unitD{
            "PL",
            "PALLET/UNIT LOAD",
            {1.0, count, commodities::packaging::pallet}},
        unitD{"PM", "pound percentage", lb* percent},
        unitD{
            "PN",
            "POUNDS NET",
            {1.0, lb, commodities::packaging::net_quantity}},
        unitD{"PO", "pound per inch of length", lb / in},
        unitD{"PP", "PLATE", {1.0, count, commodities::packaging::plate}},
        unitD{
            "PQ",
            "page per inch",
            {1.0, count / in, commodities::packaging::page}},
        unitD{"PR", "PAIR", {2, count}},
        unitD{"PS", "pound-force per square inch", pressure::psi},
        unitD{"PT", "PINT", us::pint},
        unitD{"PU", "MASS POUNDS", lb},
        unitD{"PV", "HALF PINT", half* us::pint},
        unitD{"PW", "pound per inch of width", lb / in},
        unitD{"PX", "PINT IMPERIAL", imp::pint},
        unitD{"PY", "PECK DRY (US)", us::dry::peck},
        unitD{"PZ", "PECK DRY (UK)", imp::peck},
        unitD{"Q1", "quarter(Time)", {0.25, yr}},
        unitD{"Q2", "dry pint (US)", us::dry::pint},
        unitD{"Q3", "MEAL", {1.0, count, commodities::meal}},
        unitD{"Q4", "FIFTY", {50.0, count}},
        unitD{"Q5", "TWENTY-FIVE", {25.0, count}},
        unitD{"Q6", "THIRTY-SIX", {36.0, count}},
        unitD{"Q7", "TWENTY-FOUR", {24.0, count}},
        unitD{"Q9", "FIVE", precise::one},
        unitD{
            "QA",
            "page - facsimile",
            {1.0, count, commodities::packaging::page}},
        unitD{
            "QB",
            "page - hardcopy",
            {1.0,
             count,
             commodities::package(
                 commodities::packaging::page,
                 commodities::paper)}},
        unitD{"QC", "CHANNEL", {1.0, count, commodities::channel}},
        unitD{"QD", "QUARTER DOZEN", {3, count}},
        unitD{"QE", "PHOTOGRAPHS", {1.0, count, commodities::photo}},
        unitD{"QF", "QUARTER", {0.25, one}},
        unitD{"QH", "QUARTER HOUR", {0.25, hr}},
        unitD{"QK", "QUARTER KILOGRAM", {0.25, kg}},
        unitD{
            "QR",
            "QUIRE",
            {25.0,
             count,
             commodities::package(
                 commodities::packaging::sheet,
                 commodities::paper)}},
        unitD{"QS", "QUART DRY U.S.", us::dry::quart},
        unitD{"QT", "QUART", us::quart},
        unitD{"QU", "QUART IMPERIAL", imp::quart},
        unitD{"R1", "printers pica", typographic::printers::pica},
        unitD{"R2", "becquerel", Bq},
        unitD{"R3", "revolutions per minute", rpm},
        unitD{"R4", "CALORIE", cal},
        unitD{
            "R5",
            "THOUSANDS OF DOLLARS",
            {1000.0, currency, commodities::currencies::dollar}},
        unitD{
            "R6",
            "millions of dollar",
            {1000000.0, currency, commodities::currencies::dollar}},
        unitD{
            "R7",
            "billions of dollar",
            {1000000000.0, currency, commodities::currencies::dollar}},
        unitD{"R8", "Roentgen equivalent in Man", cgs::REM},
        unitD{"R9", "THOUSAND CUBIC METERS", kilo* m.pow(3)},
        unitD{"RA", "RACK", precise_unit(count, commodities::packaging::rack)},
        unitD{"RB", "RADIAN", precise::rad},
        unitD{"RC", "ROD (AREA) - 16.25 SQUARE YARDS", {16.25, yd.pow(2)}},
        unitD{"RD", "ROD (LENGTH) - 5.5 YARDS", us::rod},
        unitD{"RE", "REEL", {1.0, count, commodities::packaging::reel}},
        unitD{"RG", "RING", precise_unit(count, commodities::packaging::ring)},
        unitD{
            "RH",
            "RUNNING OR OPERATING HOURS",
            {1.0, hr, commodities::runtime}},
        unitD{
            "RK",
            "ROLL-METRIC MEASURE",
            {1.0, count, commodities::packaging::roll}},
        unitD{"RL", "ROLL", precise_unit(count, commodities::packaging::roll)},
        unitD{"RM", "REAM", {500, count, commodities::paper}},
        unitD{"RN", "REAM-METRIC MEASURE", {500, count, commodities::paper}},
        unitD{"RO", "ROUND", {1.0, count, commodities::packaging::round}},
        unitD{
            "RP",
            "POUNDS PER REAM",
            lb / precise_unit{500, count, commodities::paper}},
        unitD{"RS", "RESETS", {1.0, count, commodities::reset}},
        unitD{"RT", "REVENUE TON MILES", currency * ton * mile},
        unitD{"RU", "RUN", {1.0, count, commodities::packaging::run}},
        unitD{"RX", "THOUSAND ROUNDS", precise::one},
        unitD{"S1", "Semester", {1.0 / 2.0, yr}},
        unitD{"S2", "Trimester", {1.0 / 3.0, yr}},
        unitD{"S3", "square foot per second", ft.pow(2) / s},
        unitD{"S4", "square metre per second", m.pow(2) / s},
        unitD{
            "S5",
            "SIXTY-FOURTHS OF AN INCH",
            precise_unit(1.0 / 64.0, precise::in)},
        unitD{"S6", "SESSIONS", {1.0, count, commodities::packaging::session}},
        unitD{
            "S7",
            "STORAGE UNITS",
            {1.0, count, commodities::packaging::storage_unit}},
        unitD{"S8", "STANDARD ADVERTISING UNIT", generate_custom_unit(380)},
        unitD{
            "S9",
            "SLIP SHEET",
            {1.0, count, commodities::packaging::slipsheet}},
        unitD{
            "SA",
            "SANDWICH",
            {1.0,
             count,
             commodities::generateHarmonizedCode(19, 05, 90, 80, false)}},
        unitD{"SB", "SQUARE MILE", precise::mile.pow(2)},
        unitD{"SC", "SQUARE CENTIMETER", precise::cm.pow(2)},
        unitD{"SD", "solid pound", {1.0, lb, commodities::packaging::bulk}},
        unitD{"SE", "SECTION (640 ACRES OR ONE SQUARE MILE)", us::section},
        unitD{"SF", "SQUARE FOOT", precise::ft.pow(2)},
        unitD{"SG", "SEGMENT", {1.0, count, commodities::packaging::segment}},
        unitD{"SH", "SHEET", {1.0, count, commodities::packaging::sheet}},
        unitD{"SI", "SQUARE INCH", precise::in.pow(2)},
        unitD{"SJ", "SACK", {1.0, count, commodities::packaging::sack}},
        unitD{
            "SK",
            "SPLIT TANKTRUCK",
            {1.0, count, commodities::packaging::split_tank_truck}},
        unitD{"SL", "SLEEVE", {1.0, count, commodities::packaging::sleeve}},
        unitD{"SM", "SQUARE METER", precise::m.pow(2)},
        unitD{"SN", "SQUARE ROD", us::rod.pow(2)},
        unitD{"SO", "SPOOL", {1.0, count, commodities::packaging::spool}},
        unitD{
            "SP",
            "SHELF PACKAGE",
            {1.0, count, commodities::packaging::shelf_package}},
        unitD{"SQ", "SQUARE", {1.0, count, commodities::packaging::square}},
        unitD{"SR", "STRIP", {1.0, count, commodities::packaging::strip}},
        unitD{
            "SS",
            "SHEET-METRIC MEASURE",
            {1.0, count, commodities::packaging::sheet}},
        unitD{"ST", "SET", {1.0, count, commodities::packaging::set}},
        unitD{"SV", "SKID", {1.0, count, commodities::packaging::skid}},
        unitD{"SW", "SKEIN", {1.0, count, commodities::packaging::skein}},
        unitD{"SX", "SHIPMENT", {1.0, count, commodities::packaging::shipment}},
        unitD{"SY", "SQUARE YARD", yd.pow(2)},
        unitD{"SZ", "SYRINGE", {1.0, count, commodities::packaging::syringe}},
        unitD{
            "T0",
            "telecommunication line in service",
            {1.0, count, commodities::linesofservice}},
        unitD{
            "T1",
            "THOUSAND POUNDS GROSS",
            {1000.0, lb, commodities::packaging::gross_quantity}},
        unitD{"T2", "thousadths of an inch", {0.001, in}},
        unitD{
            "T3",
            "THOUSAND PIECES",
            {1000.0, count, commodities::packaging::piece}},
        unitD{
            "T4",
            "THOUSAND BAGS",
            {1000.0, count, commodities::packaging::bag}},
        unitD{
            "T5",
            "THOUSAND CASINGS",
            {1000.0, count, commodities::packaging::casing}},
        unitD{"T6", "THOUSAND GALLONS", thousand* us::gallon},
        unitD{
            "T7",
            "THOUSAND IMPRESSIONS",
            {1000.0, count, commodities::impression}},
        unitD{
            "T8",
            "THOUSAND LINEAR INCHES",
            {1000.0, in, commodities::packaging::linear}},
        unitD{"T9", "THOUSAND KILOWATT HOURS", mega * W * hr},
        unitD{"TA", "TENTH CUBIC FOOT", {0.1, ft.pow(3)}},
        unitD{"TB", "TUBE", {1, count, commodities::packaging::tube}},
        unitD{"TC", "TRUCK LOAD", {1.0, count, commodities::packaging::truck}},
        unitD{"TD", "therm", energy::therm_ec},
        unitD{"TE", "tote", {1.0, count, commodities::packaging::tote}},
        unitD{"TF", "ten square yard", ten* yd.pow(2)},
        unitD{"TG", "GROSS TON", av::longton},
        unitD{"TH", "THOUSAND", precise::kilo* precise::count},
        unitD{"TI", "THOUSAND SQUARE INCHES", kilo* in.pow(2)},
        unitD{"TJ", "THOUSAND SQUARE CENTIMETERS", kilo* cm.pow(2)},
        unitD{"TK", "TANK", {1.0, count, commodities::packaging::tank}},
        unitD{
            "TL",
            "THOUSAND FOOT LINEAR",
            {1000.0, ft, commodities::packaging::linear}},
        unitD{"TM", "THOUSAND FEET (BOARD)", thousand* i::board_foot},
        unitD{"TN", "NET TON (2,000 POUNDS)", precise::one},
        unitD{"TO", "TROY OUNCE", troy::oz},
        unitD{"TP", "TEN-PACK", {10.0, count, commodities::packaging::pack}},
        unitD{"TQ", "THOUSAND FEET", kilo* ft},
        unitD{"TR", "TEN SQUARE FEET", ten* ft.pow(2)},
        unitD{"TS", "THOUSAND SQUARE FEET", kilo* ft.pow(2)},
        unitD{
            "TT",
            "THOUSAND LINEAR METRE",
            {1000.0, m, commodities::packaging::linear}},
        unitD{
            "TU",
            "THOUSAND LINEAR YARDS",
            {1000.0, yd, commodities::packaging::linear}},
        unitD{"TV", "THOUSAND KILOGRAMS", thousand* kg},
        unitD{
            "TW",
            "THOUSAND SHEETS",
            precise_unit(1.0, thousand, commodities::packaging::sheet)},
        unitD{"TX", "TROY POUND", troy::pound},
        unitD{"TY", "TRAY", {1.0, count, commodities::packaging::tray}},
        unitD{"TZ", "THOUSAND CUBIC FEET", {1000.0, ft.pow(3)}},
        unitD{
            "U1",
            "TREATMENT",
            {1.0, count, commodities::packaging::treatment}},
        unitD{"U2", "TABLET", {1.0, count, commodities::packaging::tablet}},
        unitD{"U3", "TEN", {10.0, count}},
        unitD{"U5", "TWO HUNDRED FIFTY", {250.0, count}},
        unitD{
            "U6",
            "UNITED STATES GALLONS @ 60 DEGREES FAHRENHEIT",
            precise::one},
        unitD{"UA", "torr", pressure::torr},
        unitD{
            "UB",
            "telecommunication line in service average",
            precise_unit(1.0, count, commodities::linesofservice)},
        unitD{"UC", "telecommunication port", {1.0, count, commodities::port}},
        unitD{"UD", "tenth minute", {0.1, minute}},
        unitD{"UE", "tenth hour", {0.1, hr}},
        unitD{
            "UF",
            "usage per telecommunication line average",
            count / precise_unit(1.0, one, commodities::linesofservice)},

        unitD{"UH", "TEN THOUSAND YARDS", {10000.0, yd}},
        unitD{"UL", "UNITLESS", one},
        unitD{"UM", "MILLION UNIT", mega* count},
        unitD{"UN", "UNIT", {1.0, count, commodities::packaging::unit}},
        unitD{"UP", "TROCHE", {1.0, count, commodities::packaging::trouche}},
        unitD{"UQ", "WAFER", {1.0, count, commodities::packaging::wafer}},
        unitD{"UR", "application", {1.0, count, commodities::application}},
        unitD{
            "US",
            "dosage form",
            precise_unit(1.0, count, commodities::packaging::dose)},
        unitD{"UT", "Inhalation", precise::one},
        unitD{"UU", "lozenge", {1.0, count, commodities::packaging::lozenge}},
        unitD{
            "UV",
            "percent topical only",
            {1.0, percent, commodities::packaging::topical}},
        unitD{
            "UW",
            "milliequivalent",
            {0.001, one, commodities::packaging::equivalent}},
        unitD{"UX", " DRAM", us::dram},
        unitD{"UY", "fifty square feet", {50.0, ft.pow(2)}},
        unitD{"UZ", "fifty count", {50.0, count}},
        unitD{"V1", "FLAT", {1.0, count, commodities::packaging::flat}},
        unitD{
            "V2",
            "POUCH",
            precise_unit(count, commodities::packaging::pouch)},
        unitD{"VA", "volt - ampere per kilogram", V* A / kg},
        unitD{"VC", "FIVE HUNDRED", {500.0, count}},
        unitD{"VI", "VIAL", precise_unit(count, commodities::packaging::vial)},
        unitD{"VP", "percent volume", precise_unit(0.01, pu* m.pow(3))},
        unitD{"VR", "volt ampere reactive", electrical::VAR},
        unitD{"VS", "VISIT", precise_unit(count, commodities::visit)},
        unitD{"W2", "WET KILO", precise_unit(kg, commodities::packaging::wet)},
        unitD{"WA", "watt per kilogram", W / kg},
        unitD{"WB", "WET POUND", {1.0, lb, commodities::packaging::wet}},
        unitD{"WD", "WORK DAY", {1.0, day, commodities::labor}},
        unitD{"WE", "WET TON", {1.0, ton, commodities::packaging::wet}},
        unitD{"WG", "WINE GALLON", us::gallon},
        unitD{"WH", "WHEEL", {1.0, count, commodities::packaging::wheel}},
        unitD{"WK", "WEEK", precise::time::week},
        unitD{"WP", "PENNYWEIGHT", troy::pennyweight},
        unitD{"WR", "WRAP", {1.0, count, commodities::packaging::wrap}},
        unitD{"X1", "Gunter's chain", us::engineers::chain},
        unitD{"X2", "BUNCH", {1.0, count, commodities::packaging::bunch}},
        unitD{"X3", "CLOVE", {1.0, count, commodities::packaging::clove}},
        unitD{"X4", "DROP", precise::clinical::drop},
        unitD{"X5", "HEAD", {1.0, count, commodities::packaging::head}},
        unitD{"X6", "HEART", {1.0, count, commodities::packaging::heart}},
        unitD{"X7", "LEAF", {1.0, count, commodities::packaging::leaf}},
        unitD{"X8", "LOAF", {1.0, count, commodities::packaging::loaf}},
        unitD{"X9", "PORTION", {1.0, count, commodities::packaging::portion}},
        unitD{"Y1", "SLICE", {1.0, count, commodities::packaging::slice}},
        unitD{"Y2", "TABLESPOON", precise::us::tbsp},
        unitD{"Y3", "TEASPOON", precise::us::tsp},
        unitD{"Y4", "TUB", {1.0, count, commodities::packaging::tub}},
        unitD{"YD", "YARD", precise::yd},
        unitD{
            "YL",
            "100 LINEAR YARDS",
            {100.0, yd, commodities::packaging::linear}},
        unitD{"YR", "YEAR", yr},
        unitD{"Z1", "LIFT VAN", {1.0, count, commodities::packaging::lift_van}},
        unitD{
            "Z2",
            "CHEST",
            precise_unit(count, commodities::packaging::chest)},
        unitD{"Z3", "CASK", {1.0, count, commodities::packaging::cask}},
        unitD{"Z4", "HOGSHEAD", us::hogshead},
        unitD{"Z5", "LUG", {1.0, count, commodities::packaging::lug}},
        unitD{"ZP", "PAGE", {1.0, count, commodities::packaging::page}},
        unitD{"ZW", "BARREL, DRY", us::dry::barrel},
        unitD{"ZX", "BARREL, LIQUID", us::barrel},
        unitD{"ZY", "APOTHECARY SCRUPLE", apothecaries::scruple},

    }};

    static UNITS_CPP14_CONSTEXPR_OBJECT std::array<unitD, 503> dod_units = {{
        unitD{"05", "LIFT", {1.0, count, commodities::packaging::lift}},
        unitD{"07", "STRAND", precise::one},
        unitD{"09", "TIRE", precise::one},
        unitD{"17", "100 POUND DRUM", precise::one},
        unitD{"18", "55 GALLON DRUM", precise::one},
        unitD{
            "19",
            "TANK TRUCK",
            {1.0, count, commodities::packaging::tanktruck}},
        unitD{"1N", "COUNT", precise::one},
        unitD{"1O", "SEASON", precise::one},
        unitD{"1P", "TANK CAR", {1.0, count, commodities::packaging::tankcar}},
        unitD{"1R", "TRANSACTION", precise::one},
        unitD{"1X", "QUARTER MILE", {0.25, mile}},
        unitD{"20", "20 FOOT CONTAINER", {20.0 * 8.0 * 8.5, ft.pow(3)}},
        unitD{"21", "40 FOOT CONTAINER", {40.0 * 8.0 * 8.5, ft.pow(3)}},
        unitD{"2D", "SHIP SET", precise::one},
        unitD{"2U", "MEGAGRAM", mega* g},
        unitD{"2W", "BIN", {1.0, count, commodities::packaging::bin}},
        unitD{
            "43",
            "SUPER BULK BAG (SAME SIZE AS PALLET)",
            {1.0, count, commodities::packaging::bulk_bag}},
        unitD{"44", "500 KILOGRAM BULK BAG", precise::one},
        unitD{"45", "300 KILOGRAM BULK BAG", precise::one},
        unitD{"46", "25 KILOGRAM BULK BAG", precise::one},
        unitD{"47", "50 POUND BAG", {50.0, lb, commodities::packaging::bag}},
        unitD{"48", "BULK CAR LOAD", precise::one},
        unitD{"4A", "BOBBIN", {1.0, count, commodities::packaging::bobbin}},
        unitD{"4B", "CAP", {1.0, count, commodities::packaging::cap}},
        unitD{"4D", "CURIE", precise::cgs::curie},
        unitD{"4E", "20-PACK", {20, count}},
        unitD{"4F", "100-PACK", hundred* count},
        unitD{"4G", "MICROLITER", micro* L},
        unitD{"4I", "METERS PER SECOND", precise::m / precise::s},
        unitD{
            "4J",
            "METERS PER SECOND PER SECOND",
            precise::m / precise::s.pow(2)},
        unitD{"4S", "PASCAL", precise::Pa},
        unitD{"4V", "CUBIC METER PER HOUR", precise::m.pow(3) / precise::hr},
        unitD{
            "51",
            "ACTUAL TONNES",
            {1.0, ton, commodities::packaging::actual}},
        unitD{"57", "MESH", clinical::mesh},
        unitD{"58", "NET KILOGRAMS", kg},
        unitD{"5B", "BATCH", {1.0, count, commodities::packaging::batch}},
        unitD{"5D", "PROOF GALLONS", precise::one},
        unitD{"5G", "PUMP", {1.0, count, commodities::packaging::pump}},
        unitD{"5H", "STAGE", {1.0, count, commodities::packaging::stage}},
        unitD{"5I", "STANDARD CUBE FOOT", ft.pow(3)},
        unitD{"65", "COULOMB", precise::C},
        unitD{"67", "SIEMENS", precise::S},
        unitD{"68", "AMPERE", precise::A},
        unitD{"7A", "LANDINGS", count},
        unitD{"7C", "FLIGHT HOURS", h},
        unitD{"82", "OHM", precise::ohm},
        unitD{"83", "FARAD", precise::F},
        unitD{"86", "JOULES", precise::J},
        unitD{"8C", "CORD", precise::us::cord},
        unitD{"8D", "DUTY", precise::one},
        unitD{"8P", "PROJECT", precise::one},
        unitD{"8R", "PROGRAM", precise::one},
        unitD{"8S", "SESSION", precise::one},
        unitD{"91", "STOKE", cgs::stokes},
        unitD{"94", "CURL UNIT", precise::one},
        unitD{"95", "20,000 GALLON TANKCAR", precise::one},
        unitD{"96", "10,000 GALLON TANKCAR", precise::one},
        unitD{
            "97",
            "10 KILOGRAM DRUM",
            {10.0, kg, commodities::packaging::drum}},
        unitD{"98", "15 KILOGRAM DRUM", precise::one},
        unitD{"9Y", "FAMILY UNIT", precise::one},
        unitD{"AB", "BULK PACK", precise::one},
        unitD{"AC", "ACRE", precise::acre},
        unitD{"AD", "APOTHECARY DRAM", data::byte},
        unitD{"AJ", "COP (CYLINDRICAL OR CONICAL MASS)", precise::one},
        unitD{"AL", "ACCESS LINES", precise::one},
        unitD{"AM", "AMPOULE", precise::one},
        unitD{"AO", "APOTHECARY OUNCE", apothecaries::ounce},
        unitD{"AP", "APOTHECARY POUND", {1.0, lb, commodities::aluminum}},
        unitD{"AR", "SUPPOSITORY", precise::one},
        unitD{"AS", "APOTHECARY SCRUPLE", apothecaries::scruple},
        unitD{"AT", "ATMOSPHERE", pressure::atm},
        unitD{"AV", "CAPSULE", precise::one},
        unitD{"AW", "POWDER-FILLED VIAL", precise::one},
        unitD{"AX", "TWENTY", precise::one},
        unitD{"AY", "ASSEMBLY", precise::one},
        unitD{"B0", "BRITISH THERMAL UNITS PER CUBIC FOOT", precise::one},
        unitD{"B1", "barrel (US) per day", us::barrel / day},
        unitD{"B2", "BARREL, DRY", {1.0, count, commodities::packaging::bunk}},
        unitD{"B3", "BATTING POUND", precise::one},
        unitD{"B4", "BARREL IMPERIAL", precise::one},
        unitD{"B5", "BILLET", precise::one},
        unitD{"B6", "BUN", precise::one},
        unitD{"B7", "CYCLE", precise::one},
        unitD{"B8", "BOARD", precise::one},
        unitD{"B9", "BATT", precise::one},
        unitD{"BA", "BALL", {1.0, count, commodities::packaging::bale}},
        unitD{"BB", "BASS BOX", precise::one},
        unitD{"BC", "BUCKET", precise::one},
        unitD{"BD", "BUNDLE", precise::one},
        unitD{"BE", "BALE", {1.0, count, commodities::packaging::beam}},
        unitD{"BF", "BOARD FOOT", precise::one},
        unitD{"BG", "BAG", precise::one},
        unitD{"BH", "BRUSH", precise::one},
        unitD{"BI", "BELT", precise::one},
        unitD{"BJ", "BAND", precise::one},
        unitD{"BK", "BOOK", precise::one},
        unitD{"BL", "BARREL", {1.0, count, commodities::packaging::block}},
        unitD{"BM", "BEAM", {1.0, count, commodities::packaging::bolt}},
        unitD{"BN", "BULK", precise::one},
        unitD{"BO", "BOLT", {1.0, count, commodities::packaging::bottle}},
        unitD{"BP", "100 BOARD FEET", precise::one},
        unitD{"BQ", "BRIQUET", power::hpM},
        unitD{"BR", "BAR", us::barrel},
        unitD{"BS", "BASKET", precise::one},
        unitD{"BT", "BOTTLE", {1.0, count, commodities::packaging::belt}},
        unitD{"BU", "BUSHEL (32 DRY QUARTS)", precise::one},
        unitD{"BV", "BUSHEL DRY IMPERIAL", precise::one},
        unitD{"BW", "BASE WEIGHT", precise::one},
        unitD{"BX", "BOX", precise::one},
        unitD{"BY", "BUNK", precise::one},
        unitD{"BZ", "BLOCK", mega* btu},
        unitD{"C0", "CALLS", precise::one},
        unitD{"C1", "COMPOSITE PRODUCT POUNDS (TOTAL WEIGHT)", precise::one},
        unitD{
            "C2",
            "SQUARE CENTIMETER",
            {1.0, count, commodities::packaging::carset}},
        unitD{"C3", "centilitre", centi* L},
        unitD{"C4", "CARLOAD", precise::one},
        unitD{"C5", "COST", {1.0, currency, commodities::packaging::actual}},
        unitD{"C6", "CELL", precise::one},
        unitD{"C7", "centipoise", centi* cgs::poise},
        unitD{"C8", "CUBIC DECIMETER", precise::one},
        unitD{"C9", "COIL GROUP", precise::one},
        unitD{
            "CA",
            "CARTRIDGE",
            {1.0, count, commodities::packaging::small_case}},
        unitD{"CB", "CARBOY", precise::one},
        unitD{"CC", "CUBIC CENTIMETER", cm.pow(3)},
        unitD{"CD", "carat", metric::carat},
        unitD{"CE", "degree Celsius", degC},
        unitD{"CF", "CUBIC FOOT", ft.pow(3)},
        unitD{"CG", "CENTIGRAM", {1.0, count, commodities::packaging::card}},
        unitD{"CH", "CHAIN", precise::one},
        unitD{"CI", "CUBIC INCH", in.pow(3)},
        unitD{"CK", "CAKE", precise::one},
        unitD{"CL", "COIL", {1.0, count, commodities::packaging::cylinder}},
        unitD{"CM", "CENTIMETER", cm},
        unitD{"CN", "CAN", precise::one},
        unitD{"CO", "cubic metre (net)", m.pow(3)},
        unitD{"CP", "CRATE", precise::one},
        unitD{"CQ", "CARD", precise::one},
        unitD{"CR", "CONNECTOR", m.pow(3)},
        unitD{"CS", "CASE", precise::one},
        unitD{"CT", "CARTON", precise::one},
        unitD{"CU", "CUP", precise::one},
        unitD{"CV", "COVER", precise::one},
        unitD{"CW", "HUNDRED WEIGHT (LONG)", precise::one},
        unitD{"CX", "CASSETTE", precise::one},
        unitD{"CY", "Cubic Yard", precise::one},
        unitD{"CZ", "CUBIC METER", precise::one},
        unitD{"DA", "DAY", precise::one},
        unitD{"DB", "dry pound", {1.0, lb, commodities::packaging::dry}},
        unitD{"DC", "disk (disc)", {1.0, count, commodities::packaging::disk}},
        unitD{"DE", "deal", {1.0, count, commodities::packaging::deal}},
        unitD{"DF", "FAHRENHEIT", precise::one},
        unitD{"DG", "DECIGRAM", precise::one},
        unitD{"DI", "DISPENSER", precise::one},
        unitD{"DK", "DEGREES, KELVIN", precise::one},
        unitD{"DL", "DECILITER", precise::one},
        unitD{"DM", "DRAM", precise::one},
        unitD{"DO", "DOLLARS U.S.", precise::one},
        unitD{"DP", "DOZEN PAIR", precise::one},
        unitD{"DQ", "DATA RECORD", precise::one},
        unitD{"DR", "DRUM", precise::one},
        unitD{"DS", "DISPLAY", precise::one},
        unitD{"DT", "DRY TON", precise::one},
        unitD{"DU", "DYNE", cgs::dyn},
        unitD{"DW", "PENNYWEIGHT", precise::one},
        unitD{"DX", "dyne per centimetre", cgs::dyn / cm},
        unitD{"DY", "DIRECTORY BOOKS", precise::one},
        unitD{"DZ", "DOZEN", {12, count}},
        unitD{"E1", "HECTOMETER", precise::one},
        unitD{"EA", "EACH", one},
        unitD{"EB", "ELECTRONIC MAIL BOXES", precise::one},
        unitD{"EE", "EMPLOYEES", precise::one},
        unitD{"EH", "KNOTS", precise::one},
        unitD{"EJ", "LOCATIONS", precise::one},
        unitD{"EP", "ELEVEN PACK", {11, one}},
        unitD{"EQ", "EQUIVALENT GALLONS", precise::one},
        unitD{"EV", "ENVELOPES", precise::one},
        unitD{"F4", "MINIM", precise::one},
        unitD{"F6", "PRICE PER SHARE", precise::one},
        unitD{"FA", "FATHOM", precise::one},
        unitD{"FB", "FIELDS", precise::one},
        unitD{"FC", "1000 CUBIC FEET", precise::one},
        unitD{"FD", "FOLD", precise::one},
        unitD{"FE", "TRACK FOOT", precise::one},
        unitD{"FF", "HUNDRED CUBIC METERS", precise::one},
        unitD{"FG", "TRANSDERMAL PATCH", precise::one},
        unitD{"FJ", "SIZING FACTOR", ratio},
        unitD{"FK", "FIBER", precise::one},
        unitD{"FL", "FLAKE TON", precise::one},
        unitD{"FM", "MILLION CUBIC FEET", precise::one},
        unitD{"FO", "FLUID OUNCE", precise::one},
        unitD{"FR", "foot per minute", ft / minute},
        unitD{"FT", "FOOT", precise::one},
        unitD{"FU", "FURLONG", precise::one},
        unitD{"FV", "FIVE", precise::one},
        unitD{"FY", "FIFTY", precise::one},
        unitD{"GB", "GALLONS PER MINUTE", precise::one},
        unitD{"GG", "GREAT GROSS", precise::one},
        unitD{"GI", "GILL (IMPERIAL)", precise::one},
        unitD{"GL", "GALLON", precise::one},
        unitD{"GM", "GRAM", precise::one},
        unitD{"GN", "GRAIN", precise::one},
        unitD{"GP", "GROUP", precise::one},
        unitD{"GR", "GROSS", precise::one},
        unitD{"GT", "THOUSAND GALLONS PER DAY", precise::one},
        unitD{"GX", "APOTHECARY GRAIN", precise::one},
        unitD{"H2", "HALF LITER", precise::one},
        unitD{"H4", "HECTOLITER", precise::one},
        unitD{"HA", "HUNDRED CUBIC FEET", precise::one},
        unitD{"HB", "HOSPITAL BEDS", precise::one},
        unitD{"HC", "HUNDRED COUNT", precise::one},
        unitD{"HD", "HUNDRED", precise::one},
        unitD{"HF", "HUNDRED FEET", precise::one},
        unitD{"HG", "HECTOGRAM", precise::one},
        unitD{"HH", "HOGSHEAD", precise::one},
        unitD{"HI", "HUNDRED SHEETS", precise::one},
        unitD{"HK", "HANK", precise::one},
        unitD{"HL", "HUNDRED FEET (LINEAR)", precise::one},
        unitD{"HO", "HUNDRED TROY OUNCES", precise::one},
        unitD{"HP", "HUNDRED POUNDS", precise::one},
        unitD{"HQ", "HECTARE", precise::one},
        unitD{"HR", "HOUR", precise::one},
        unitD{"HS", "HUNDRED SQUARE FEET", precise::one},
        unitD{"HT", "HALF HOUR", precise::one},
        unitD{"HW", "HUNDRED WEIGHT - SHORT (HUNDRED WEIGHT)", precise::one},
        unitD{"HX", "HUNDRED BOXES", precise::one},
        unitD{"HY", "HUNDRED YARDS", precise::one},
        unitD{"HZ", "HALF DOZEN", precise::one},
        unitD{"I1", "PERSONS, CAPACITY", precise::one},
        unitD{"IG", "IMPERIAL GALLON", precise::one},
        unitD{"IH", "INHALER", precise::one},
        unitD{"IM", "IMPRESSION", precise::one},
        unitD{"IN", "INCH", precise::one},
        unitD{"IP", "INSURANCE POLICY", precise::one},
        unitD{"IS", "STOP", precise::one},
        unitD{"IU", "INTERNATIONAL UNIT", precise::one},
        unitD{"JB", "JOB", precise::one},
        unitD{"JG", "JUG", precise::one},
        unitD{"JO", "JOINT", precise::one},
        unitD{"JR", "JAR", precise::one},
        unitD{"JU", "JUMBO", precise::one},
        unitD{"K2", "SQUARE KILOMETER", precise::one},
        unitD{"K6", "KILOLITER", precise::one},
        unitD{"K7", "KILOWATT", precise::one},
        unitD{"K9", "kilogram per millimeter squared", kg / mm.pow(2)},
        unitD{"KC", "kilogram per cubic meter", kg / m.pow(3)},
        unitD{"KE", "KEG", precise::one},
        unitD{"KF", "KILOPACKET", precise::one},
        unitD{"KG", "KILOGRAM", kg},
        unitD{"KH", "HUNDREDS OF KILOGRAMS", precise::one},
        unitD{"KK", "100 KILOGRAMS", precise::one},
        unitD{"KM", "kilogram per square meter", kg / m.pow(2)},
        unitD{"KR", "KARAT (CARAT)", precise::one},
        unitD{"KT", "KIT", precise::one},
        unitD{"KU", "TASK", precise::one},
        unitD{"KV", "KILOVOLT", precise::electrical::kV},
        unitD{"KZ", "KILOWATT-HOUR", precise::kWh},
        unitD{"L5", "LITERS AT 15 DEGREES CELSIUS", precise::one},
        unitD{"LB", "POUND (AVOIRDUPOIS)", precise::one},
        unitD{"LE", "LITE", precise::one},
        unitD{"LF", "LINEAR FOOT", precise::one},
        unitD{"LG", "LENGTH", precise::one},
        unitD{"LI", "LITER", precise::one},
        unitD{"LJ", "LARGE SPRAY", precise::one},
        unitD{"LK", "LINK", precise::one},
        unitD{"LM", "LINEAR METER", precise::one},
        unitD{"LN", "LINEAR INCH", precise::one},
        unitD{"LO", "LONG TON", precise::one},
        unitD{"LR", "LAYER", precise::one},
        unitD{"LS", "LUMP SUM", precise::one},
        unitD{"LT", "LOT", precise::one},
        unitD{"LY", "LINEAR YARD", precise::one},
        unitD{"M0", "MAGNETIC TAPE", precise::one},
        unitD{"M2", "SQUARE MILE", precise::one},
        unitD{"M3", "MAT", precise::one},
        unitD{"M5", "MICROGRAM", precise::one},
        unitD{"M6", "METRIC TON", precise::one},
        unitD{"MA", "METRIC NET TON", precise::one},
        unitD{"MB", "BRITISH THERMAL UNITS/HOUR", precise::btu / precise::hr},
        unitD{"MC", "THOUSAND CUBIC FEET", precise::one},
        unitD{"MD", "AIR DRY METRIC TON", precise::one},
        unitD{"ME", "MEAL", precise::one},
        unitD{"MF", "THOUSAND FEET", precise::one},
        unitD{"MG", "MILLIGRAM", precise::mg},
        unitD{"MH", "METRIC", precise::one},
        unitD{"MI", "MILE", precise::one},
        unitD{"MJ", "METRIC GROSS TON", precise::one},
        unitD{"MK", "METRIC LONG TON", precise::one},
        unitD{"ML", "MILLILITER", precise::one},
        unitD{"MM", "MILLIMETER", precise::mm},
        unitD{"MO", "MONTH", precise::one},
        unitD{"MQ", "1000 METERS", precise::one},
        unitD{"MR", "METER", precise::one},
        unitD{"MS", "SQUARE MILLIMETER", precise::one},
        unitD{"MT", "MINUTE", precise::one},
        unitD{"MX", "THOUSAND", precise::one},
        unitD{"MZ", "MIXED", precise::one},
        unitD{"N2", "NUMBER OF LINES", precise::one},
        unitD{"N7", "PART", precise::one},
        unitD{"N9", "CARTRIDGE NEEDLE", precise::one},
        unitD{"NB", "BARGE", precise::one},
        unitD{"NC", "CAR", precise::one},
        unitD{"ND", "NET BARRELS", precise::one},
        unitD{"NE", "NET LITERS", precise::one},
        unitD{"NF", "MESSAGES", precise::one},
        unitD{"NG", "NET GALLONS", precise::one},
        unitD{"NI", "NET IMPERIAL GALLONS", precise::one},
        unitD{"NJ", "NUMBER OF SCREENS", precise::one},
        unitD{"NK", "NIGHTS", precise::one},
        unitD{"NL", "LOAD", precise::one},
        unitD{"NM", "NAUTICAL MILE", precise::one},
        unitD{"NN", "TRAIN", precise::one},
        unitD{"NS", "SHORT TON", precise::one},
        unitD{"NT", "TRAILER", precise::one},
        unitD{"NV", "VEHICLE", precise::one},
        unitD{"NX", "PARTS PER THOUSAND", precise::one},
        unitD{"OA", "PANEL", precise::one},
        unitD{"OC", "BILLBOARD", precise::one},
        unitD{"OL", "OUTLET", precise::one},
        unitD{"OP", "TWO PACK", precise::one},
        unitD{"OT", "OUTFIT", precise::one},
        unitD{"OU", "OPERATING UNIT", precise::one},
        unitD{"OZ", "AV OUNCE", precise::one},
        unitD{"P0", "PAGE - ELECTRONIC", precise::one},
        unitD{"P1", "PERCENT", precise::one},
        unitD{"P2", "POUNDS PER FOOT", precise::one},
        unitD{"P3", "THREE PACK", precise::one},
        unitD{"P4", "FOUR PACK", precise::one},
        unitD{"P5", "FIVE PACK", precise::one},
        unitD{"P6", "SIX PACK", precise::one},
        unitD{"P7", "SEVEN PACK", precise::one},
        unitD{"P8", "EIGHT PACK", precise::one},
        unitD{"P9", "NINE PACK", precise::one},
        unitD{"PA", "PAGE", precise::one},
        unitD{"PB", "PAIR INCHES", precise::one},
        unitD{"PC", "PIECE", precise::one},
        unitD{"PD", "PAD", precise::one},
        unitD{"PE", "POUNDS EQUIVALENT", precise::one},
        unitD{"PF", "PALLET (LIFT)", precise::one},
        unitD{"PG", "PACKAGE", precise::one},
        unitD{"PH", "PACK (PAK)", precise::one},
        unitD{"PI", "PILLOW", precise::one},
        unitD{"PJ", "PALLET/UNIT LOAD", precise::one},
        unitD{"PK", "PECK DRY US", precise::one},
        unitD{"PL", "PAIL", precise::one},
        unitD{"PM", "PLATE", precise::one},
        unitD{"PN", "PERSON", precise::one},
        unitD{"PO", "POUNDS GROSS", precise::one},
        unitD{"PP", "PINT IMPERIAL", precise::one},
        unitD{"PQ", "PECK DRY IMPERIAL", precise::one},
        unitD{"PR", "PAIR", precise::one},
        unitD{"PS", "POUNDS NET", precise::one},
        unitD{"PT", "PINT", precise::one},
        unitD{"PU", "MASS POUNDS", precise::one},
        unitD{"PV", "HALF PINT", precise::one},
        unitD{"PX", "PELLET", precise::one},
        unitD{"PY", "PITCH", precise::one},
        unitD{"PZ", "PACKET", precise::one},
        unitD{"QC", "CHANNEL", precise::one},
        unitD{"QE", "PHOTOGRAPHS", precise::one},
        unitD{"QF", "QUARTER", precise::one},
        unitD{"QI", "QUART IMPERIAL", precise::one},
        unitD{"QK", "QUARTER KILOGRAM", precise::one},
        unitD{"QR", "QUIRE", precise::one},
        unitD{"QS", "QUART DRY U.S.", precise::one},
        unitD{"QT", "QUART", precise::one},
        unitD{"QU", "QUARTER DOZEN", precise::one},
        unitD{"R4", "CALORIE", precise::one},
        unitD{"R5", "THOUSANDS OF DOLLARS", precise::one},
        unitD{"R9", "THOUSAND CUBIC METERS", precise::one},
        unitD{"RA", "RATION", precise::one},
        unitD{"RB", "RADIAN", precise::one},
        unitD{"RC", "ROD (AREA) - 16.25 SQUARE YARDS", precise::one},
        unitD{"RD", "ROD (LENGTH) - 5.5 YARDS", precise::one},
        unitD{"RE", "ROUND", precise::one},
        unitD{"RG", "RING", precise::one},
        unitD{"RH", "RUNNING OR OPERATING HOURS", precise::one},
        unitD{"RK", "ROLL-METRIC MEASURE", precise::one},
        unitD{"RL", "REEL", precise::one},
        unitD{"RM", "REAM", precise::one},
        unitD{"RN", "REAM-METRIC MEASURE", precise::one},
        unitD{"RO", "ROLL", precise::one},
        unitD{"RP", "POUNDS PER REAM", precise::one},
        unitD{"RR", "RACK", precise::one},
        unitD{"RS", "RESETS", precise::one},
        unitD{"RT", "REVENUE TON MILES", precise::one},
        unitD{"RU", "RUN", precise::one},
        unitD{"RX", "THOUSAND ROUNDS", precise::one},
        unitD{"S5", "SIXTY-FOURTHS OF AN INCH", precise::one},
        unitD{"S6", "SESSIONS", precise::one},
        unitD{"S7", "STORAGE UNITS", precise::one},
        unitD{"S8", "SHELF PACKAGE", precise::one},
        unitD{"S9", "SLIP SHEET", precise::one},
        unitD{"SA", "SANDWICH", precise::one},
        unitD{"SB", "SHIPMENT", precise::one},
        unitD{"SC", "SECOND", precise::one},
        unitD{"SD", "SKID", precise::one},
        unitD{"SE", "SET", precise::one},
        unitD{"SF", "SQUARE FOOT", precise::one},
        unitD{"SG", "SEGMENT", precise::one},
        unitD{"SH", "SHEET", precise::one},
        unitD{"SI", "SQUARE INCH", precise::one},
        unitD{"SJ", "SACK", precise::one},
        unitD{"SK", "SKEIN", precise::one},
        unitD{"SL", "SPOOL", precise::one},
        unitD{"SM", "SQUARE METER", precise::one},
        unitD{"SN", "SECTION (640 ACRES OR ONE SQUARE MILE)", precise::one},
        unitD{"SO", "SHOT", precise::one},
        unitD{"SP", "STRIP", precise::one},
        unitD{"SQ", "SQUARE", precise::one},
        unitD{"SR", "SPLIT TANKTRUCK", precise::one},
        unitD{"SS", "SHEET-METRIC MEASURE", precise::one},
        unitD{"ST", "SEAT", precise::one},
        unitD{"SU", "SQUARE ROD", precise::one},
        unitD{"SV", "SLEEVE", precise::one},
        unitD{"SW", "STANDARD ADVERTISING UNIT", precise::one},
        unitD{"SX", "STICK", precise::one},
        unitD{"SY", "SQUARE YARD", precise::yd.pow(2)},
        unitD{"SZ", "SYRINGE", precise::one},
        unitD{"T1", "THOUSAND POUNDS GROSS", precise::one},
        unitD{"T2", "TEASPOON", precise::us::tsp},
        unitD{"T3", "THOUSAND PIECES", precise::one},
        unitD{"T4", "THOUSAND BAGS", precise::one},
        unitD{"T5", "THOUSAND CASINGS", precise::one},
        unitD{"T6", "THOUSAND GALLONS", precise::one},
        unitD{"T7", "THOUSAND IMPRESSIONS", precise::one},
        unitD{"T8", "THOUSAND LINEAR INCHES", precise::one},
        unitD{"T9", "THOUSAND KILOWATT HOURS/MEGAWATT-HOUR", precise::one},
        unitD{"TA", "TENTH CUBIC FOOT", precise::one},
        unitD{"TB", "TABLESPOON", precise::one},
        unitD{"TC", "TRUCK LOAD", precise::one},
        unitD{"TD", "therm", energy::therm_ec},
        unitD{"TE", "TEN", precise::ten},
        unitD{"TF", "TWENTY-FIVE", precise_unit(25.0, precise::one)},
        unitD{"TG", "GROSS TON", precise::one},
        unitD{"TH", "THOUSAND KILOGRAMS", precise::kilo* precise::kilogram},
        unitD{"TI", "THOUSAND SQUARE INCHES", precise::one},
        unitD{"TJ", "THOUSAND SQUARE CENTIMETERS", precise::one},
        unitD{"TK", "TANK", precise::one},
        unitD{"TL", "THOUSAND LINEAR METERS", precise::one},
        unitD{"TM", "THOUSAND FEET (BOARD)", precise::one},
        unitD{"TN", "NET TON (2,000 POUNDS)", precise::one},
        unitD{"TO", "TROY OUNCE", precise::troy::oz},
        unitD{"TP", "TROY POUND", precise::troy::pound},
        unitD{"TQ", "THOUSAND FEET", precise::one},
        unitD{"TR", "TEN SQUARE FEET", precise::one},
        unitD{"TS", "THIRTY-SIX", precise::one},
        unitD{"TT", "TABLET", precise::one},
        unitD{"TU", "TUBE", precise::one},
        unitD{"TV", "TEN-PACK", precise::one},
        unitD{"TW", "THOUSAND SHEETS", precise::one},
        unitD{"TX", "THOUSAND LINEAR YARDS", precise::one},
        unitD{"TY", "TRAY", precise::one},
        unitD{"TZ", "THOUSAND SQUARE FEET", precise::one},
        unitD{"U1", "TREATMENT", precise::one},
        unitD{"U5", "TWO HUNDRED FIFTY", precise::one},
        unitD{
            "U6",
            "UNITED STATES GALLONS @ 60 DEGREES FAHRENHEIT",
            precise::one},
        unitD{
            "UB",
            "telecommunication line in service average",
            precise_unit(1.0, count, commodities::linesofservice)},
        unitD{"UC", "telecommunication port", {1.0, count, commodities::port}},
        unitD{
            "UF",
            "usage per telecommunication line average",
            count / precise_unit(1.0, one, commodities::linesofservice)},
        unitD{"UH", "TEN THOUSAND YARDS", precise_unit(10000.0, precise::yd)},
        unitD{"UL", "UNITLESS", precise::one},
        unitD{"UM", "MILLION UNITS", precise::one},
        unitD{"UN", "UNIT", precise::one},
        unitD{"UP", "TROCHE", precise::one},
        unitD{"UQ", "WAFER", precise::one},
        unitD{"US", "United States Pharmacopoeia Unit", precise::one},
        unitD{"UT", "Inhalation", precise::one},
        unitD{"V1", "FLAT", precise::one},
        unitD{"V2", "POUCH", precise::one},
        unitD{"VA", "volt - ampere per kilogram", V* A / kg},
        unitD{"VC", "FIVE HUNDRED", precise::one},
        unitD{"VI", "VIAL", precise::one},
        unitD{"VS", "VISIT", precise::one},
        unitD{"VT", "VOLT", precise::one},
        unitD{"W2", "WET KILO", precise::one},
        unitD{"WA", "watt per kilogram", W / kg},
        unitD{"WB", "WET POUND", precise::one},
        unitD{"WD", "WORK DAY", precise::one},
        unitD{"WE", "WET TON", precise::one},
        unitD{"WG", "WINE GALLON", precise::one},
        unitD{"WH", "WHEEL", precise::one},
        unitD{"WK", "WEEK", precise::one},
        unitD{"WR", "WRAP", precise::one},
        unitD{"WT", "WATT", precise::one},
        unitD{"X2", "BUNCH", precise::one},
        unitD{"X3", "CLOVE", precise::one},
        unitD{"X4", "DROP", precise::one},
        unitD{"X5", "HEAD", precise::one},
        unitD{"X6", "HEART", precise::one},
        unitD{"X7", "LEAF", precise::one},
        unitD{"X8", "LOAF", precise::one},
        unitD{"X9", "PORTION", precise::one},
        unitD{"Y1", "SLICE", precise::one},
        unitD{"Y4", "TUB", precise::one},
        unitD{"YD", "YARD", precise::yd},
        unitD{"YL", "100 LINEAL YARDS", precise::one},
        unitD{"YR", "YEAR", precise::yr},
        unitD{"YT", "BYTE", precise::data::byte},
        unitD{"Z1", "LIFT VAN", precise::one},
        unitD{"Z2", "CHEST", precise::one},
        unitD{"Z3", "CASK", precise::one},
        unitD{"Z5", "LUG", precise::one},
        unitD{
            "ZF",
            "MILLION BTUS/DEKATHERM",
            precise::mega* precise::btu /
                precise_unit(10.0, precise::energy::therm_ec)},
    }};

}  // namespace precise

precise_unit x12_unit(const std::string& x12_string)
{
    // NOLINTNEXTLINE (readability-qualified-auto)
    auto ind = std::lower_bound(
        precise::x12_units.begin(),
        precise::x12_units.end(),
        x12_string,
        [](const precise::unitD& u_set, const std::string& val) {
            return (strcmp(std::get<0>(u_set), val.c_str()) < 0);
        });
    if (ind == precise::x12_units.end()) {
        return precise::invalid;
    }
    if (strcmp(std::get<0>(*ind), x12_string.c_str()) == 0) {
        return std::get<2>(*ind);
    }
    return precise::invalid;
}

precise_unit dod_unit(const std::string& dod_string)
{
    // NOLINTNEXTLINE (readability-qualified-auto)
    auto ind = std::lower_bound(
        precise::dod_units.begin(),
        precise::dod_units.end(),
        dod_string,
        [](const precise::unitD& u_set, const std::string& val) {
            return (strcmp(std::get<0>(u_set), val.c_str()) < 0);
        });
    if (ind == precise::dod_units.end()) {
        return x12_unit(dod_string);
    }
    if (strcmp(std::get<0>(*ind), dod_string.c_str()) == 0) {
        return std::get<2>(*ind);
    }
    return x12_unit(dod_string);
}

#ifdef ENABLE_UNIT_MAP_ACCESS
namespace detail {
    const void* x12rawData(size_t& array_size)
    {
        array_size = precise::x12_units.size();
        return precise::x12_units.data();
    }
    const void* dodrawData(size_t& array_size)
    {
        array_size = precise::dod_units.size();
        return precise::dod_units.data();
    }
}  // namespace detail

#endif

}  // namespace UNITS_NAMESPACE
