/*
Copyright (c) 2019-2025,
Lawrence Livermore National Security, LLC;
See the top-level NOTICE for additional details. All rights reserved.
SPDX-License-Identifier: BSD-3-Clause
*/
#include "units.hpp"

#include <algorithm>
#include <array>
#include <cstring>
#include <string>
#include <tuple>

namespace UNITS_NAMESPACE {

    namespace precise{
using unitD = std::tuple<const char*, const char*, precise_unit>;
static UNITS_CPP14_CONSTEXPR_OBJECT std::array<unitD, 623> x12_units{{
    unitD{"03", "SECOND", precise::s},
    unitD{"05", "LIFT", {1.0, count, commodities::packaging::lift}},
    unitD{"07", "STRAND", precise::one},
    unitD{"09", "TIRE", precise::one},
    unitD{"10", "GROUP", {1.0, count, commodities::packaging::group}},
    unitD{"11", "OUTFIT", {1.0, count, commodities::packaging::outfit}},
    unitD{"12", "PACKET", precise::one},
    unitD{"13", "RATION", {1.0, count, commodities::packaging::ration}},
    unitD{"14", "SHOT",  precise::us::shot},
    unitD{"15", "STICK", {1.0, count, commodities::packaging::stick}},
    unitD{"17", "100 POUND DRUM", precise_unit(100.0, precise::lb)},
    unitD{"18", "55 GALLON DRUM", precise_unit(55.0, precise::lb)},
    unitD{"19", "TANK TRUCK", {1.0, count, commodities::packaging::tanktruck}},
    unitD{"1A", "CAR MILE", {1.0, mile, commodities::packaging::car}},
    unitD{"1B", "CAR COUNT", {1.0, count, commodities::packaging::car}},
    unitD{"1D", "CABOOSE COUNT", {1.0, count, commodities::packaging::caboose}},
    unitD{"1E", "CAR COUNT", {1.0, count, commodities::packaging::car}},
    unitD{"1G", "GALLON", us::gallon},
    unitD{"1H", "CABOOSE MILE", {1.0, mile, commodities::packaging::caboose}},
    unitD{"1I", "FIXED RATE", {1.0, count, commodities::packaging::fixed_rate}},
    unitD{"1N", "COUNT", precise::count},
    unitD{"1O", "SEASON", precise::one},
    unitD{"1P", "TANK CAR", {1.0, count, commodities::packaging::tankcar}},
    unitD{"1Q", "FRAME", precise::one},
    unitD{"1R", "TRANSACTION", precise::one},
    unitD{"1X", "QUARTER MILE", precise_unit(0.25, precise::mile)},
    unitD{"20", "20 FOOT CONTAINER", {20.0 * 8.0 * 8.5, ft.pow(3)}},
    unitD{"21", "40 FOOT CONTAINER", {40.0 * 8.0 * 8.5, ft.pow(3)}},
    unitD{"22", "DECILITER PER GRAM", deci* L / g},
    unitD{"23", "DENSITY (METRIC)", g / cm.pow(3)},
    unitD{
        "24",
        "THEORETICAL POUND",
        {1.0, lb, commodities::packaging::theoretical}},
    unitD{"25", "DENSITY PER SQUARE CENTIMETER", g / cm.pow(2)},
    unitD{"26", "ACTUAL TONS", {1.0, ton, commodities::packaging::actual}},
    unitD{
        "27",
        "THEORETICAL TON",
        {1.0, ton, commodities::packaging::theoretical}},
    unitD{"2D", "SHIP SET", precise::one},
    unitD{"2G", "volt AC", V},
    unitD{"2H", "volt DC", V},
    unitD{"2I", "BRITISH THERMAL UNITS/HOUR", precise::btu / precise::hr},
    unitD{"2J", "CUBIC CENTIMETER PER SECOND", cm.pow(3) / s},
    unitD{"2K", "CUBIC FEET PER HOUR", ft.pow(3) / hr},
    unitD{"2L", "CUBIC FEET PER MINUTE", ft.pow(3) / minute},
    unitD{"2M", "CENTIMETER PER SECOND", cm / s},
    unitD{"2N", "DECIBEL", log::dB},
    unitD{"2R", "KILOCURIE", kilo* cgs::curie},
    unitD{"2U", "MEGAGRAM", precise::mega* precise::g},
    unitD{"2V", "MEGAGRAM PER HOUR", mega* g / hr},
    unitD{"2W", "BIN", {1.0, count, commodities::packaging::bin}},
    unitD{"2X", "METRE PER MINUTE", m / minute},
    unitD{"30", "HORSEPOWER DAYS PER AIR DRY METRIC TONS", hp* day / precise_unit(t, commodities::packaging::dry)},
    unitD{"31", "POUND UNIT", pu* lb},
    unitD{"36", "CFM", ft.pow(3) / minute / ft.pow(2)},
    unitD{"3B", "MEGAJOULE", mega* J},
    unitD{"3C", "MANMONTH", {1.0, time::mog, commodities::people}},
    unitD{"41", "MILLILITRE PER MINUTE", mL / minute},
    unitD{"43", "SUPER BULK BAG (SAME SIZE AS PALLET)", {1.0, count, commodities::packaging::bulk_bag}},
    unitD{"44", "500 KILOGRAM BULK BAG", precise_unit(500.0, precise::kg)},
    unitD{"45", "300 KILOGRAM BULK BAG", precise_unit(300.0, precise::kg)},
    unitD{"46", "25 KILOGRAM BULK BAG", precise_unit(25.0, precise::kg)},
    unitD{"47", "50 POUND BAG", precise_unit(50.0, precise::kg)},
    unitD{"48", "BULK CAR LOAD", precise::one},
    unitD{"4A", "BOBBIN", {1.0, count, commodities::packaging::bobbin}},
    unitD{"4B", "CAP", {1.0, count, commodities::packaging::cap}},
    unitD{"4C", "CENTISTOKE", cgs::stokes* centi},
    unitD{"4D", "CURIE", cgs::curie},
    unitD{"4E", "20-PACK", precise_unit(20, precise::count)},
    unitD{"4F", "100-PACK", precise_unit(100, precise::count)},
    unitD{"4G", "MICROLITER", precise::micro* precise::L},
    unitD{"4I", "METERS PER SECOND", precise::m / precise::s},
    unitD{"4J", "METERS PER SECOND PER SECOND", m / s.pow(2)},
    unitD{"4L", "MEGABYTE", data::MB},
    unitD{"4N", "MEGABECQUEREL", mega* becquerel},
    unitD{"4S", "PASCAL", Pa},
    unitD{"4V", "CUBIC METER PER HOUR", m.pow(3) / hr},
    unitD{
        "50",
        "ACTUAL KILOGRAMS",
    {1.0, kg, commodities::packaging::actual}},
    unitD{"51", "ACTUAL TONNES", {1.0, ton, commodities::packaging::actual}},
    unitD{
        "53",
        "THEORETICAL KILOGRAM",
        {1.0, kg, commodities::packaging::theoretical}},
    unitD{
        "54",
        "THEORETICAL TONNE",
        {1.0, mass::tonne, commodities::packaging::theoretical}},
    unitD{"57", "MESH",  precise::clinical::mesh},
    unitD{"58", "NET KILOGRAMS", kg},
    unitD{"5A", "BARREL PER MINUTE", us::barrel / minute},
    unitD{"5B", "BATCH", {1.0, count, commodities::packaging::batch}},
    unitD{"5C", "GALLON PER 1000 UNITS", us::gallon / (kilo * count)},
    unitD{"5D", "PROOF GALLONS", {1.0, gal, commodities::package(commodities::packaging::equivalent, commodities::chemicals::alcohol)}},
    unitD{"5E", "MILLION CUBIC FEET PER DAY", precise::mega* precise::energy::scf / day},
    unitD{"5G", "PUMP", {1.0, count, commodities::packaging::pump}},
    unitD{"5H", "STAGE", {1.0, count, commodities::packaging::stage}},
    unitD{"5I", "STANDARD CUBE FOOT", ft.pow(3)},
    unitD{"5K", "ITEMS PER MINUTE", count / minute},
    unitD{"63", "FAILURES PER SECOND", {1.0, count / s, commodities::failure}},
    unitD{"65", "COULOMB", C},
    unitD{"67", "SIEMENS", S},
    unitD{"68", "AMPERE", A},
    unitD{"69", "TEST SPECIFIC SCALE", generate_custom_unit(333)},
    unitD{"70", "VOLT", precise::volt},
    unitD{"73", "AMPERE-TURN PER CENTIMETER", precise::A* precise::count / cm},
    unitD{"76", "GAUSS", cgs::gauss},
    unitD{"7A", "LANDINGS", count},
    unitD{"7C", "FLIGHT HOURS", h},
    unitD{"81", "HENRY", henry},
    unitD{"82", "OHM", ohm},
    unitD{"83", "FARAD", F},
    unitD{"85", "FOOT-POUND", ft* lbf},
    unitD{"86", "JOULES", J},
    unitD{"8C", "CORD", precise::us::cord},
    unitD{"8D", "DUTY", precise::one},
    unitD{"8P", "PROJECT", precise::one},
    unitD{"8R", "PROGRAM", precise::one},
    unitD{"8S", "SESSION", precise::one},
    unitD{"8U", "SQUARE KILOMETER", precise::km.pow(2)},
    unitD{"91", "STOKE",  precise::cgs::stokes},
    unitD{"92", "CALORIE PER CUBIC CENTIMETER", cal / cm.pow(3)},
    unitD{"93", "CALORIE PER GRAM", cal / g},
    unitD{"94", "CURL UNIT", generate_custom_unit(335)},
    
unitD{
        "95",
        "20,000 GALLON TANKCAR",
        precise_unit(20000, precise::gal) / precise::count},
    unitD{
        "96",
        "10,000 GALLON TANKCAR",
        precise_unit(10000, precise::gal) / precise::count},
    unitD{"97", "ten kg drum", {10.0, kg, commodities::packaging::drum}},
    unitD{
        "98",
        "15 KILOGRAM DRUM",
        precise_unit(15, precise::kg) / precise::count},
    unitD{"99", "WATT", precise::watt},
    unitD{"9A", "APOTHECARY POUND", precise::apothecaries::pound},
    unitD{"9B", "BRIQUET", precise::one},
    unitD{"9F", "FOLD", precise::one},
    unitD{"9O", "APOTHECARY OUNCE", precise::apothecaries::ounce},
    unitD{"9P", "PILLOW", precise::one},
    unitD{"9S", "SEAT", precise::one},
    unitD{"9Y", "FAMILY UNIT", precise::one},
    unitD{"9Z", "USP UNIT", precise::one},
    unitD{"A8", "AMPERE-SECOND", A*s},
    unitD{ "AA", "BALL", {1.0, count, commodities::packaging::ball} },
    unitD{"AB", "BULK PACK", precise::one},
    unitD{"AC", "ACRE", acre},
    unitD{"AD", "BYTE", precise::B},
    unitD{"AE", "AMPERE PER METER", A / m},
    unitD{"AF", "CENTIGRAM", centi* g},
    unitD{"AG", "ANGSTROM", distance::angstrom},
    unitD{"AH", "MINUTE", minute},
    unitD{"AI", "MINUTES PER CALL", minute / precise_unit(one, commodities::call)},
    unitD{"AJ", "COP (CYLINDRICAL OR CONICAL MASS)", {1.0, count, commodities::packaging::cop}},
    unitD{"AK", "FATHOM", nautical::fathom},
    unitD{ "AL", "ACCESS LINES", {1.0, count, commodities::linesofservice} },
    unitD{ "AM", "AMPOULE", {1.0, count, commodities::packaging::ampoule} },
    unitD{"AO", "Ampere-turn", A* count},
    unitD{"AP", "aluminium pound only", {1.0, lb, commodities::aluminum}},
    unitD{"AQ", "AHF UNITS", clinical::AHF},
    unitD{"AR", "SUPPOSITORY", precise::one},
    unitD{"AS", "ASSORTMENT", precise::one},
    unitD{"AT", "ATMOSPHERE", pressure::atm},
    unitD{ "AV", "CAPSULE", {1.0, count, commodities::packaging::capsule} },
    unitD{"AW", "POWDER-FILLED VIAL", precise::one},
    unitD{"AX", "TWENTY", precise_unit(20.0, precise::one)},
    unitD{ "AY", "ASSEMBLY", {1.0, count, commodities::packaging::assembly} },
    unitD{"AZ", "BTU PER POUND", energy::btu_it / lb},
    unitD{
        "B0",
        "BRITISH THERMAL UNITS PER CUBIC FOOT",
        precise::btu / (precise::ft.pow(3))},
    unitD{"B2", "BUNK", precise::one},
    unitD{ "B3", "BATTING POUND", {1.0, lb, commodities::fiber} },
    unitD{"B4", "BARREL IMPERIAL", imp::winebarrel},
    unitD{ "B5", "BILLET", {1.0, count, commodities::packaging::billet} },
    unitD{"B6", "BUN", milli* mol / L},
    unitD{"B7", "CYCLE", {constants::tau, rad}},
    unitD{"B8", "BOARD", {1.0, count, commodities::packaging::board}},
    unitD{"B9", "BATT", {1.0, count, commodities::packaging::batt}},
    unitD{"BA", "BALE", precise::one},
    unitD{"BB", "BASS BOX", {1.0, count, commodities::packaging::base_box}},
    unitD{"BC", "BUCKET", {1.0, count, commodities::packaging::bucket}},
    unitD{"BD", "BUNDLE", {1.0, count, commodities::packaging::bundle}},
    unitD{"BE", "BEAM", precise::one},
    unitD{"BF", "BOARD FOOT", i::board_foot},
    unitD{"BG", "BAG", {1.0, count, commodities::packaging::bag}},
    unitD{"BH", "BRUSH", {1.0, count, commodities::packaging::brush}},
    unitD{"BI", "BAR", {1.0, count, commodities::packaging::bar}},
    unitD{"BJ", "BAND", {1.0, count, commodities::packaging::band}},
    unitD{"BK", "BOOK", {1.0, count, commodities::packaging::book}},
    unitD{"BL", "BLOCK", precise::one},
    unitD{"BM", "BOLT", precise::one},
    unitD{"BN", "BULK", precise_unit(count, commodities::packaging::bulk)},
    unitD{"BO", "BOTTLE", precise::one},
    unitD{"BP", "100 BOARD FEET", hundred* i::board_foot},
    unitD{"BQ", "brake horse power", power::hpM},
    unitD{"BR", "BARREL", precise::us::barrel},
    unitD{"BS", "BASKET", {1.0, count, commodities::packaging::basket}},
    unitD{"BT", "BELT", precise::one},
    unitD{"BU", "BUSHEL (32 DRY QUARTS)", us::dry::bushel},
    unitD{"BV", "BUSHEL DRY IMPERIAL", imp::bushel},
    unitD{"BW", "BASE WEIGHT", kg},
    unitD{"BX", "BOX", {1.0, count, commodities::packaging::box}},
    unitD{
        "BY",
        "British thermal unit (BTU)",
        energy::btu_it},
    unitD{"BZ", "MILLION BTUS", mega* btu},
    unitD{"C0", "CALLS", precise::one},
    unitD{"C1", "COMPOSITE PRODUCT POUNDS (TOTAL WEIGHT)", {1.0, lb, commodities::packaging::composite}},
    unitD{"C2", "CARSET", precise::one},
    unitD{"C4", "CARLOAD", {1.0, count, commodities::packaging::car}},
    unitD{"C5", "COST", precise::currency},
    unitD{"C6", "CELL", {1.0, count, commodities::packaging::cell}},
    unitD{"C8", "CUBIC DECIMETER", (deci * m).pow(3)},
    unitD{"C9", "COIL GROUP", precise::one},
    unitD{"CA", "CASE", precise::one},
    unitD{"CB", "CARBOY", {1.0, count, commodities::packaging::carboy}},
    unitD{"CC", "CUBIC CENTIMETER", precise::cm.pow(3)},
    unitD{"CD", "KARAT (CARAT)", precise::one},
    unitD{"CF", "CUBIC FOOT", precise::ft.pow(3)},
    unitD{"CG", "CARD", precise::one},
    unitD{"CH", "CONTAINER", precise::one},
    unitD{"CI", "CUBIC INCH", precise::in.pow(3)},
    unitD{"CJ", "CONE", {1.0, count, commodities::packaging::cone}},
    unitD{"CK", "CONNECTOR", precise::one},
    unitD{"CL", "CYLINDER", precise::one},
    unitD{"CM", "CENTIMETER", precise::cm},
    unitD{"CN", "CAN", {1.0, count, commodities::packaging::can}},
    unitD{"CP", "CRATE", {1.0, count, commodities::packaging::crate}},
    unitD{"CQ", "CARTRIDGE", precise::one},
    unitD{"CR", "CUBIC METER", precise::m.pow(3)},
    unitD{"CS", "CASSETTE", precise::one},
    unitD{"CT", "CARTON", {1.0, count, commodities::packaging::carton}},
    unitD{"CU", "CUP", us::cup},
    unitD{"CV", "COVER", {1.0, count, commodities::packaging::cover}},
    unitD{"CW", "HUNDRED POUNDS", precise_unit(100.0, precise::lb)},
    unitD{"CX", "COIL", precise::one},
    unitD{"CY", "CUBIC YARD", precise::yd.pow(3)},
    unitD{"CZ", "COMBO", precise::one},
    unitD{"D1", "INVERSE SECOND PER RADIAN SQUARED", s.inv() / rad.pow(2)},
    unitD{"D2", "INVERSE SECOND PER RADIAN SQUARED PER METER SQUARED", s.inv() / (rad.pow(2) * m.pow(2))},
    unitD{"D8", "CUSTOM UNIT 341", generate_custom_unit(341)},
    unitD{"D9", "DYNE PER SQUARE CENTIMETER", cgs::dyn / cm.pow(2)},
    unitD{"DA", "DAY", precise::time::day},
    unitD{"DD", "DEGREE", deg},
    unitD{"DF", "DRAM", apothecaries::drachm},
    unitD{"DG", "DECIGRAM", precise_unit(0.1, precise::kilogram)},
    unitD{"DH", "MILE", precise::mile},
    unitD{"DI", "DISPENSER", precise::one},
    unitD{"DJ", "DECAGRAM", precise_unit(10.0, precise::g)},
    unitD{"DK", "KILOMETER", precise::km},
    unitD{"DL", "DECILITER", deci* L},
    unitD{"DM", "DECIMETER", deci* m},
    unitD{"DN", "DECIMETER-NEWTON", deci * N * m},
    unitD{"DO", "DOLLARS U.S.", precise::currency},
    unitD{"DP", "DOZEN PAIR", precise_unit(24.0, count)},
    unitD{"DQ", "DATA RECORD", {1.0, count, commodities::record}},
    unitD{"DR", "DRUM", {1.0, count, commodities::packaging::drum}},
    unitD{"DS", "DISPLAY", {1.0, count, commodities::packaging::display}},
    unitD{"DT", "DRY TON", {1.0, ton, commodities::packaging::dry}},
    unitD{"DU", "DYNE", precise::cgs::dyn},
    unitD{"DV", "DEGREES, KELVIN", precise::K},
    unitD{"DW", "CALENDAR DAYS (NUMBER OF)", precise::time::day},
    unitD{"DY", "DIRECTORY BOOKS", precise::one},
    unitD{"DZ", "DOZEN", precise_unit(12, precise::one)},
    unitD{"E1", "HECTOMETER", precise_unit(100, precise::m)},
    unitD{"EA", "EACH", precise::count},
    unitD{"EB", "ELECTRONIC MAIL BOXES", precise::one},
    unitD{"EC", "INVERSE SECOND", one / time::moj},
    unitD{"EE", "EMPLOYEES", precise::one},
    unitD{"EH", "KNOTS", precise::nautical::knot},
    unitD{"EJ", "LOCATIONS", precise::one},
    unitD{"EP", "ELEVEN PACK", precise_unit(11, precise::one)},
    unitD{"EQ", "EQUIVALENT GALLONS", gal},
    unitD{"EV", "ENVELOPES", {1.0, count, commodities::packaging::envelope}},
    unitD{"F2", "INTERNATIONAL UNIT", precise::one},
    unitD{"F4", "MINIM", precise::one},
    unitD{"F6", "PRICE PER SHARE", precise::currency / precise::count},
    unitD{"F9", "FIBERS PER MILLILITER", precise_unit(count, commodities::fiber) / precise_unit(cm.pow(3), commodities::air)},
    unitD{"FA", "FAHRENHEIT", degF},
    unitD{"FB", "FIELDS", {1.0, count, commodities::packaging::field}},
    unitD{"FC", "1000 CUBIC FEET", precise::kilo* precise::ft.pow(3)},
    unitD{"FE", "TRACK FOOT", {1.0, ft, commodities::packaging::track}},
    unitD{"FF", "HUNDRED CUBIC METERS", precise_unit(100.0, precise::m.pow(3))},
    unitD{"FG", "TRANSDERMAL PATCH", precise::one},
    unitD{"FJ", "SIZING FACTOR", precise::one},
    unitD{"FK", "FIBER", precise::one},
    unitD{"FL", "FLAKE TON", {1.0, ton, commodities::packaging::flake}},
    unitD{"FM", "MILLION CUBIC FEET", precise::mega* precise::ft.pow(3)},
    unitD{"FO", "FLUID OUNCE", precise::us::floz},
    unitD{"FS", "FEET PER SECOND", ft / s},
    unitD{"FT", "FOOT", precise::ft},
    unitD{"FU", "FURLONG", precise::one},
    unitD{"G2", "GALLONS PER MINUTE", us::gallon / minute},
    unitD{"G5", "GILL (IMPERIAL)", imp::gill},
    unitD{"GA", "GALLON", us::gallon},
    unitD{"GC", "PERCENT", g / (hecto * g)},
    unitD{"GD", "ITEMS PER BARREL", {144.0, count, commodities::packaging::barrel}},
    unitD{"GF", "GRAMS PER METER", g / m},
    unitD{"GG", "GREAT GROSS", {1728.0, count}},
    unitD{"GH", "HALF GALLON", {0.5, us::gallon}},
    unitD{"GI", "IMPERIAL GALLON", imp::gallon},
    unitD{"GJ", "GRAM PER MILLILITER", g / mL},
    unitD{"GK", "GRAM PER KILOGRAM", g / kg},
    unitD{"GR", "GRAM", precise::g},
    unitD{"GS", "GROSS", {144.0, count}},
    unitD{"GV", "GIGAJOULE", giga* J},
    unitD{"GW", "GALLONS PER THOUSAND CUBIC FEET", us::gallon / (kilo * ft.pow(3))},
    unitD{"GX", "GRAIN", i::grain},
    unitD{"GY", "YARD", yd},
    unitD{"GZ", "GRAYVALUE", eflag},
    unitD{"H1", "HALF ITEM", {0.5, count, commodities::packaging::page_electronic}},
    unitD{"H2", "HALF LITER", half* L},
    unitD{"H4", "HECTOLITER", hecto* L},
    unitD{"HA", "HANK", precise::one},
    unitD{"HB", "HUNDRED BOXES", precise::one},
    unitD{"HC", "HUNDRED COUNT", hundred* count},
    unitD{"HD", "HALF DOZEN", precise::one},
    unitD{"HF", "HUNDRED FEET", hundred* foot},
    unitD{"HG", "HECTOGRAM", hecto* g},
    unitD{"HH", "HUNDRED CUBIC FEET", precise_unit(100.0, precise::ft.pow(3))},
    unitD{"HI", "HUNDRED SHEETS", precise::one},
    unitD{"HJ", "HORSEPOWER METRIC", precise::power::hpM},
    unitD{"HK", "HUNDRED KILOGRAM", hundred* kg},
    unitD{"HL", "HUNDRED FOOT (LINEAR)", {100.0, ft, commodities::packaging::linear}},
    unitD{"HO", "HUNDRED TROY OUNCES", hundred* troy::oz},
    unitD{"HQ", "HECTARE", precise::one},
    unitD{"HR", "HOUR", precise::hr},
    unitD{"HS", "HUNDRED SQUARE FEET", precise_unit(100.0, precise::ft.pow(2))},
    unitD{"HT", "HALF HOUR", half* hr},
    unitD{"HU", "HUNDRED", hundred* count},
    unitD{"HV", "HUNDRED WEIGHT - SHORT (HUNDRED WEIGHT)", precise::one},
    unitD{"HW", "HUNDRED WEIGHT (LONG)", av::longhundredweight},
    unitD{"HX", "HOSPITAL BEDS", precise::one},
    unitD{"HY", "HUNDRED YARDS", hundred* yd},
    unitD{"I2", "PELLET", precise::one},
    unitD{"IC", "ITEMS PER INCH", count / in},
    unitD{"IE", "PERSON", {1.0, count, commodities::person}},
    unitD{"IH", "INHALER", precise::one},
    unitD{"II", "INCHES OF WATER", pressure::inH2O* eflag},
    unitD{"IL", "INCHES PER MINUTE", in / minute},
    unitD{"IM", "IMPRESSION", {1.0, count, commodities::impression}},
    unitD{"IN", "INCH", precise::in},
    unitD{"IP", "INSURANCE POLICY", {1.0, count, commodities::policy}},
    unitD{"IS", "STOP", precise::one},
    unitD{"IT", "ITEMS PER CENTIMETER", count / cm},
    unitD{"IV", "INCHES PER SECOND SQUARED", in / s.pow(2)},
    unitD{"JA", "JOB", precise::one},
    unitD{"JB", "JUMBO", precise::one},
    unitD{"JE", "JOULE PER KELVIN", J / K},
    unitD{"JK", "MEGAJOULE PER KILOGRAM", mega* J / kg},
    unitD{"JM", "MEGAJOULE PER CUBIC METRE", mega* J / m.pow(3)},
    unitD{"JO", "JOINT", {1.0, count, commodities::packaging::joint}},
    unitD{"JR", "JAR", {1.0, count, commodities::packaging::jar}},
    unitD{"JU", "JUG", precise::one},
    unitD{"K1", "KILOWATT", electrical::kW},
    unitD{"K3", "KILOVOLT-AMPERE-REACTIVE-HOUR", electrical::kVAR* hr},
    unitD{"K5", "KILOVOLT-AMPERE-REACTIVE", kilo* electrical::VAR},
    unitD{"K6", "KILOLITER", kilo* L},
    unitD{"K7", "KILOWATT", precise::electrical::kW},
    unitD{"K8", "KILOVOLT", precise::electrical::kV},
    unitD{"KA", "CAKE", {1.0, count, commodities::packaging::cake}},
    unitD{"KB", "KILOBYTE", {1.0, kilo* count, commodities::character}},
    unitD{"KD", "KILOGRAM", kg},
    unitD{"KE", "KEG", {1.0, count, commodities::packaging::keg}},
    unitD{"KF", "KILOPACKET", precise::one},
    unitD{"KG", "KILOGRAM", precise::kg},
    unitD{"KH", "KILOWATT-HOUR", precise::kWh},
    unitD{"KI", "KILOGRAM PER MILLIMETER", kg / mm},
    unitD{"KJ", "THOUSAND ITEMS", {1.0, kilo* count, commodities::packaging::segment}},
    unitD{"KK", "100 KILOGRAMS", precise_unit(100.0, precise::kg)},
    unitD{"KL", "KILOGRAM PER METER", kg / m},
    unitD{"KO", "THOUSAND PER GRAM", {1.0, milli / g, commodities::package(commodities::packaging::equivalent, commodities::chemicals::KOH)}},
    unitD{"KPA", "KILOPASCAL", kilo* Pa},
    unitD{"KS", "THOUSAND PSI", thousand* lb / in.pow(2)},
    unitD{"KT", "KIT", {1.0, count, commodities::packaging::kit}},
    unitD{"KU", "TASK", precise::one},
    unitD{"KV", "KELVIN", precise::K},
    unitD{"KVR", "KILOVOLT-AMPERE-REACTIVE", kilo* electrical::VAR},
    unitD{"KW", "KILOGRAM PER MILLIMETER", kg / mm},
    unitD{"KX", "MILLILITERS PER KILOGRAM", mL / kg},
    unitD{"L5", "LITERS AT 15 DEGREES CELSIUS", precise::one},
    unitD{"LA", "POUND PER CUBIC INCH", lb / in.pow(3)},
    unitD{"LB", "POUND (AVOIRDUPOIS)", lb},
    unitD{"LC", "CENTIMETER LINEAR", {1.0, cm, commodities::packaging::linear}},
    unitD{"LD", "LITER PER DAY", L / day},
    unitD{"LE", "LITE", {1.0, count, commodities::packaging::lite}},
    unitD{"LF", "LINEAR FOOT", {1.0, ft, commodities::packaging::linear}},
    unitD{"LG", "LONG TON", av::longton},
    unitD{"LH", "LABOR HOUR", {1.0, hr, commodities::labor}},
    unitD{"LI", "LINEAR INCH", {1.0, in, commodities::packaging::linear}},
    unitD{"LJ", "LARGE SPRAY", precise::one},
    unitD{"LK", "LINK", {1.0, count, commodities::packaging::length}},
    unitD{"LM", "LINEAR METER", {1.0, m, commodities::packaging::linear}},
    unitD{"LN", "LENGTH", precise::one},
    unitD{"LO", "LOT", precise::one},
    unitD{"LR", "LAYER", {1.0, count, commodities::packaging::layer}},
    unitD{"LS", "LUMP SUM", {1.0, currency, commodities::packaging::lump}},
    unitD{"LT", "LITER", L},
    unitD{"LX", "YARD LINEAR PER POUND", precise_unit(1.0, yd, commodities::packaging::linear) / lb},
    unitD{"LY", "LINEAR YARD", {1.0, yd, commodities::packaging::linear}},
    unitD{"M0", "MAGNETIC TAPE", precise::one},
    unitD{"M1", "MILLIGRAM PER LITER", mg / L},
    unitD{"M3", "MAT", {1.0, count, commodities::packaging::mat}},
    unitD{"M4", "CURRENCY", currency},
    unitD{"M7", "MICROINCH", micro* in},
    unitD{"M8", "MEGAPASCAL", mega* Pa},
    unitD{"M9", "MILLION BTU PER THOUSAND CUBIC FEET", mega* btu / (thousand * ft.pow(3))},
    unitD{"MAL", "MEGALITER", mega* L},
    unitD{"MC", "MICROGRAM", micro* g},
    unitD{"MCU", "MILLICURIE", milli* cgs::curie},
    unitD{"MD", "AIR DRY METRIC TON", precise_unit(mass::tonne, commodities::packaging::dry)},
    unitD{"ME", "MILLIGRAM", precise::mg},
    unitD{"MG", "METRIC GROSS TON", precise::one},
    unitD{"MI", "METRIC", precise::one},
    unitD{"MIL", "THOUSAND ITEMS", thousand* count},
    unitD{"MIN", "MINUTE", minute},
    unitD{"MIU", "MILLION INTERNATIONAL UNITS", mega* laboratory::IU},
    unitD{"MJ", "MINUTE", precise::minute},
    unitD{"ML", "MILLILITER", precise::milli* precise::L},
    unitD{"MLD", "BILLION ITEMS", giga* count},
    unitD{"MM", "MILLIMETER", mm},
    unitD{"MN", "METRIC NET TON", {1.0, ton, commodities::packaging::net_quantity}},
    unitD{"MO", "MONTH", time::moj},
    unitD{"MP", "METRIC TON", mass::tonne},
    unitD{"MPA", "MEGAPASCAL", mega* Pa},
    unitD{"MQ", "1000 METERS", thousand* m},
    unitD{"MR", "METER", precise::m},
    unitD{"MS", "SQUARE MILLIMETER", precise::mm.pow(2)},
    unitD{"MT", "METRIC LONG TON", precise::one},
    unitD{"MTK", "SQUARE METER", m.pow(2)},
    unitD{"MTR", "METER", m},
    unitD{"MV", "ITEMS", count},
    unitD{"MWH", "MEGAWATT-HOUR", mega * W * hr},
    unitD{"MX", "MIXED", precise::one},
    unitD{"N2", "NUMBER OF LINES", precise::one},
    unitD{"N6", "MEGAHERTZ", mega* Hz},
    unitD{"N7", "PART", precise::one},
    unitD{"N9", "CARTRIDGE NEEDLE", precise::one},
    unitD{"NB", "BARGE", {1.0, count, commodities::packaging::barge}},
    unitD{"NC", "CAR", {1.0, count, commodities::packaging::car}},
    unitD{"ND", "NET BARRELS", {1.0, us::barrel, commodities::packaging::net_quantity}},
    unitD{"NE", "NET LITERS", {1.0, L, commodities::packaging::net}},
    unitD{"NF", "MESSAGES", {1.0, count, commodities::message}},
    unitD{"NG", "NET GALLONS", {1.0, gal, commodities::packaging::net}},
    unitD{"NH", "MESSAGE HOUR", {1.0, hr, commodities::message}},
    unitD{"NI", "NET IMPERIAL GALLONS", {1.0, imp::gallon, commodities::packaging::net}},
    unitD{"NJ", "NUMBER OF SCREENS", {1.0, count, commodities::screen}},
    unitD{"NK", "NIGHTS", precise::one},
    unitD{"NL", "LOAD", {1.0, count, commodities::packaging::load}},
    unitD{"NM", "NAUTICAL MILE", nautical::mile},
    unitD{"NN", "TRAIN", {1.0, count, commodities::packaging::train}},
    unitD{"NS", "SHORT TON", av::ton},
    unitD{"NT", "TRAILER", precise::one},
    unitD{"NV", "VEHICLE", {1.0, count, commodities::vehicle}},
    unitD{"NX", "PARTS PER THOUSAND", milli* count},
    unitD{"NZ", "THOUSAND GALLONS PER DAY", precise::one},
    unitD{"OA", "PANEL", {1.0, count, commodities::packaging::panel}},
    unitD{"OB", "OUTLET", precise::one},
    unitD{"OC", "BILLBOARD", precise::one},
    unitD{"OG", "APOTHECARY GRAIN", precise::one},
    unitD{"OP", "TWO PACK", {2, count}},
    unitD{"OU", "OPERATING UNIT", precise::one},
    unitD{"OZ", "OUNCE - AV", av::ounce},
    unitD{"P0", "PAGE - ELECTRONIC", precise::one},
    unitD{"P1", "PERCENT", percent},
    unitD{"P2", "POUNDS PER FOOT", lb / ft},
    unitD{"P3", "THREE PACK", {3, one}},
    unitD{"P4", "FOUR PACK", {4, count}},
    unitD{"P5", "FIVE PACK", {5, one}},
    unitD{"P6", "SIX PACK", {6, one}},
    unitD{"P7", "SEVEN PACK", {7, one}},
    unitD{"P8", "EIGHT PACK", {8, one}},
    unitD{"P9", "NINE PACK", {9, one}},
    unitD{"PA", "PAIL", precise::one},
    unitD{"PB", "PAIR INCHES", {2, count* in}},
    unitD{"PC", "PIECE", count},
    unitD{"PD", "PAD", {1.0, count, commodities::packaging::pad}},
    unitD{"PE", "POUNDS EQUIVALENT", {10.0, lb, commodities::packaging::equivalent}},
    unitD{"PF", "PALLET (LIFT)", precise::one},
    unitD{"PG", "POUNDS GROSS", lb},
    unitD{"PH", "PACK (PAK)", precise::one},
    unitD{"PI", "PITCH", {1.0, count / in, commodities::character}},
    unitD{"PK", "PACKAGE", precise::one},
    unitD{"PL", "PALLET/UNIT LOAD", precise::one},
    unitD{"PN", "POUNDS NET", {1.0, lb, commodities::packaging::net_quantity}},
    unitD{"PP", "PLATE", precise::one},
    unitD{"PR", "PAIR", {2, count}},
    unitD{"PT", "PINT", us::pint},
    unitD{"PU", "MASS POUNDS", lb},
    unitD{"PV", "HALF PINT", half* us::pint},
    unitD{"PX", "PINT IMPERIAL", imp::pint},
    unitD{"PY", "PECK DRY (US)", us::dry::peck},
    unitD{"PZ", "PECK DRY (UK)", imp::peck},
    unitD{"Q3", "MEAL", {1.0, count, commodities::meal}},
    unitD{"Q4", "FIFTY", precise::one},
    unitD{"Q5", "TWENTY-FIVE", precise::one},
    unitD{"Q6", "THIRTY-SIX", precise::one},
    unitD{"Q7", "TWENTY-FOUR", precise::one},
    unitD{"Q9", "FIVE", precise::one},
    unitD{"QC", "CHANNEL", precise::one},
    unitD{"QD", "QUARTER DOZEN", {3, count}},
    unitD{"QE", "PHOTOGRAPHS", precise::one},
    unitD{"QF", "QUARTER", precise::one},
    unitD{"QH", "QUARTER HOUR", {0.25, hr}},
    unitD{"QK", "QUARTER KILOGRAM", {0.25, kg}},
    unitD{"QR", "QUIRE", precise::one},
    unitD{"QS", "QUART DRY U.S.", us::dry::quart},
    unitD{"QT", "QUART", us::quart},
    unitD{"QU", "QUART IMPERIAL", imp::quart},
    unitD{"R4", "CALORIE", cal},
    unitD{"R5", "THOUSANDS OF DOLLARS", precise::one},
    unitD{"R9", "THOUSAND CUBIC METERS", kilo* m.pow(3)},
    unitD{"RA", "RACK", precise::one},
    unitD{"RB", "RADIAN", precise::rad},
    unitD{"RC", "ROD (AREA) - 16.25 SQUARE YARDS", precise::one},
    unitD{"RD", "ROD (LENGTH) - 5.5 YARDS", us::rod},
    unitD{"RE", "REEL", precise::one},
    unitD{"RG", "RING", precise_unit(count, commodities::packaging::ring)},
    unitD{"RH", "RUNNING OR OPERATING HOURS", {1.0, hr, commodities::runtime}},
    unitD{"RK", "ROLL-METRIC MEASURE", precise::one},
    unitD{"RL", "ROLL", precise::one},
    unitD{"RM", "REAM", {500, count, commodities::paper}},
    unitD{"RN", "REAM-METRIC MEASURE", {500, count, commodities::paper}},
    unitD{"RO", "ROUND", precise::one},
    unitD{"RP", "POUNDS PER REAM", lb / precise_unit{500, count, commodities::paper}},
    unitD{"RS", "RESETS", {1.0, count, commodities::reset}},
    unitD{"RT", "REVENUE TON MILES", currency * ton * mile},
    unitD{"RU", "RUN", {1.0, count, commodities::packaging::run}},
    unitD{"RX", "THOUSAND ROUNDS", precise::one},
    unitD{
        "S5",
        "SIXTY-FOURTHS OF AN INCH",
        precise_unit(1.0 / 64.0, precise::in)},    
unitD{"S6", "SESSIONS", {1.0, count, commodities::packaging::session}},
    unitD{"S7", "STORAGE UNITS", precise::one},
    unitD{"S8", "STANDARD ADVERTISING UNIT", generate_custom_unit(380)},
    unitD{"S9", "SLIP SHEET", precise::one},
    unitD{"SA", "SANDWICH", precise::one},
    unitD{"SB", "SQUARE MILE", precise::mile.pow(2)},
    unitD{"SC", "SQUARE CENTIMETER", precise::cm.pow(2)},
    unitD{"SE", "SECTION (640 ACRES OR ONE SQUARE MILE)", us::section},
    unitD{"SF", "SQUARE FOOT", precise::ft.pow(2)},
    unitD{"SG", "SEGMENT", {1.0, count, commodities::packaging::segment}},
    unitD{"SH", "SHEET", {1.0, count, commodities::packaging::sheet}},
    unitD{"SI", "SQUARE INCH", precise::in.pow(2)},
    unitD{"SJ", "SACK", {1.0, count, commodities::packaging::sack}},
    unitD{"SK", "SPLIT TANKTRUCK", precise::one},
    unitD{"SL", "SLEEVE", precise::one},
    unitD{"SM", "SQUARE METER", precise::m.pow(2)},
    unitD{"SN", "SQUARE ROD", us::rod.pow(2)},
    unitD{"SO", "SPOOL", precise::one},
    unitD{"SP", "SHELF PACKAGE", precise::one},
    unitD{"SQ", "SQUARE", {1.0, count, commodities::packaging::square}},
    unitD{"SR", "STRIP", precise::one},
    unitD{"SS", "SHEET-METRIC MEASURE", precise::one},
    unitD{"ST", "SET", precise::one},
    unitD{"SV", "SKID", precise::one},
    unitD{"SW", "SKEIN", precise::one},
    unitD{"SX", "SHIPMENT", precise::one},
    unitD{"SY", "SQUARE YARD", yd.pow(2)},
    unitD{"SZ", "SYRINGE", precise::one},
    unitD{"T1", "THOUSAND POUNDS GROSS", {1000.0, lb, commodities::packaging::gross_quantity}},
    unitD{"T3", "THOUSAND PIECES", precise::one},
    unitD{"T4", "THOUSAND BAGS", precise::one},
    unitD{"T5", "THOUSAND CASINGS", precise::one},
    unitD{"T6", "THOUSAND GALLONS", thousand* us::gallon},
    unitD{"T7", "THOUSAND IMPRESSIONS", precise::one},
    unitD{"T8", "THOUSAND LINEAR INCHES", {1000.0, in, commodities::packaging::linear}},
    unitD{"T9", "THOUSAND KILOWATT HOURS/MEGAWATT-HOUR", mega * W * hr},
    unitD{"TA", "TENTH CUBIC FOOT", {0.1, ft.pow(3)}},
    unitD{"TB", "TUBE", precise::one},
    unitD{"TC", "TRUCK LOAD", {1.0, count, commodities::packaging::truck}},
    unitD{"TG", "GROSS TON", av::longton},
    unitD{"TH", "THOUSAND", precise::kilo* precise::count},
    unitD{"TI", "THOUSAND SQUARE INCHES", kilo* in.pow(2)},
    unitD{"TJ", "THOUSAND SQUARE CENTIMETERS", kilo* cm.pow(2)},
    unitD{"TK", "TANK", precise::one},
    unitD{"TL", "THOUSAND FOOT LINEAR", {1000.0, ft, commodities::packaging::linear}},
    unitD{"TM", "THOUSAND FEET (BOARD)", thousand* i::board_foot},
    unitD{"TN", "NET TON (2,000 POUNDS)", precise::one},
    unitD{"TO", "TROY OUNCE", troy::oz},
    unitD{"TP", "TEN-PACK", precise::one},
    unitD{"TQ", "THOUSAND FEET", kilo* ft},
    unitD{"TR", "TEN SQUARE FEET", ten* ft.pow(2)},
    unitD{"TS", "THOUSAND SQUARE FEET", kilo* ft.pow(2)},
    unitD{"TT", "THOUSAND LINEAR METRE", {1000.0, m, commodities::packaging::linear}},
    unitD{"TU", "THOUSAND LINEAR YARDS", {1000.0, yd, commodities::packaging::linear}},
    unitD{"TV", "THOUSAND KILOGRAMS", thousand* kg},
    unitD{"TW", "THOUSAND SHEETS", precise::one},
    unitD{"TX", "TROY POUND", troy::pound},
    unitD{"TY", "TRAY", precise::one},
    unitD{"TZ", "THOUSAND CUBIC FEET", precise::one},
    unitD{"U1", "TREATMENT", precise::one},
    unitD{"U2", "TABLET", precise::one},
    unitD{"U3", "TEN", precise::one},
    unitD{"U5", "TWO HUNDRED FIFTY", precise::one},
    unitD{"U6", "UNITED STATES GALLONS @ 60 DEGREES FAHRENHEIT", precise::one},
    unitD{
        "UD",
        "TENTH MINUTE",
        {0.1, minute}},
    unitD{
        "UE",
        "TENTH HOUR",
        {0.1, hr}},
    unitD{"UH", "TEN THOUSAND YARDS", {10000.0, yd}},
    unitD{"UL", "UNITLESS", precise::one},
    unitD{"UM", "MILLION UNITS", mega* count},
    unitD{"UN", "UNIT", precise::one},
    unitD{"UP", "TROCHE", precise::one},
    unitD{"UQ", "WAFER", precise::one},
    unitD{"UX", "APOTHECARY DRAM", precise::one},
    unitD{"V1", "FLAT", precise::one},
    unitD{"V2", "POUCH", precise::one},
    unitD{"VC", "FIVE HUNDRED", precise::one},
    unitD{"VI", "VIAL", precise_unit(count, commodities::packaging::vial)},
    unitD{"VS", "VISIT", precise_unit(count, commodities::visit)},
    unitD{"W2", "WET KILO", precise_unit(kg, commodities::packaging::wet)},
    unitD{"WB", "WET POUND", {1.0, lb, commodities::packaging::wet}},
    unitD{"WD", "WORK DAY", precise::one},
    unitD{"WE", "WET TON", {1.0, ton, commodities::packaging::wet}},
    unitD{"WG", "WINE GALLON", precise::one},
    unitD{"WH", "WHEEL", precise::one},
    unitD{"WK", "WEEK", precise::time::week},
    unitD{"WP", "PENNYWEIGHT", precise::one},
    unitD{"WR", "WRAP", precise::one},
    unitD{"X1", "CHAIN", precise::one},
    unitD{"X2", "BUNCH", precise::one},
    unitD{"X3", "CLOVE", precise::one},
    unitD{"X4", "DROP", precise::one},
    unitD{"X5", "HEAD", precise::one},
    unitD{"X6", "HEART", precise::one},
    unitD{"X7", "LEAF", precise::one},
    unitD{"X8", "LOAF", precise::one},
    unitD{"X9", "PORTION", precise::one},
    unitD{"Y1", "SLICE", precise::one},
    unitD{"Y2", "TABLESPOON", precise::us::tbsp},
    unitD{"Y3", "TEASPOON", precise::us::tsp},
    unitD{"Y4", "TUB", precise::one},
    unitD{"YD", "YARD", precise::yd},
    unitD{"YL", "100 LINEAL YARDS", precise::one},
    unitD{"YR", "YEAR", precise::one},
    unitD{"Z1", "LIFT VAN", precise::one},
    unitD{"Z2", "CHEST", precise::one},
    unitD{"Z3", "CASK", precise::one},
    unitD{"Z4", "HOGSHEAD", precise::one},
    unitD{"Z5", "LUG", precise::one},
    unitD{"ZP", "PAGE", precise::one},
    unitD{"ZW", "BARREL, DRY", precise::one},
    unitD{"ZX", "BARREL, LIQUID", precise::one},
    unitD{"ZY", "APOTHECARY SCRUPLE", precise::one},
}};

static UNITS_CPP14_CONSTEXPR_OBJECT std::array<unitD, 498> dod_units = {{
    unitD{"05", "LIFT", {1.0, count, commodities::packaging::lift}},
    unitD{"07", "STRAND", precise::one},
    unitD{"09", "TIRE", precise::one},
    unitD{"17", "100 POUND DRUM", precise::one},
    unitD{"18", "55 GALLON DRUM", precise::one},
    unitD{"19", "TANK TRUCK", {1.0, count, commodities::packaging::tanktruck}},
    unitD{"1N", "COUNT", precise::one},
    unitD{"1O", "SEASON", precise::one},
    unitD{"1P", "TANK CAR", {1.0, count, commodities::packaging::tankcar}},
    unitD{"1R", "TRANSACTION", precise::one},
    unitD{"1X", "QUARTER MILE", {0.25, mile}},
    unitD{"20", "20 FOOT CONTAINER", {20.0 * 8.0 * 8.5, ft.pow(3)}},
    unitD{"21", "40 FOOT CONTAINER", {40.0 * 8.0 * 8.5, ft.pow(3)}},
    unitD{"2D", "SHIP SET", precise::one},
    unitD{"2U", "MEGAGRAM", mega* g},
    unitD{"2W", "BIN", {1.0, count, commodities::packaging::bin}},
    unitD{"43", "SUPER BULK BAG (SAME SIZE AS PALLET)", {1.0, count, commodities::packaging::bulk_bag}},
    unitD{"44", "500 KILOGRAM BULK BAG", precise::one},
    unitD{"45", "300 KILOGRAM BULK BAG", precise::one},
    unitD{"46", "25 KILOGRAM BULK BAG", precise::one},
    unitD{"47", "50 POUND BAG", {50.0, lb, commodities::packaging::bag}},
    unitD{"48", "BULK CAR LOAD", precise::one},
    unitD{"4A", "BOBBIN", {1.0, count, commodities::packaging::bobbin}},
    unitD{"4B", "CAP", {1.0, count, commodities::packaging::cap}},
    unitD{"4D", "CURIE", precise::cgs::curie},
    unitD{"4E", "20-PACK", {20, count}},
    unitD{"4F", "100-PACK", hundred* count},
    unitD{"4G", "MICROLITER", micro* L},
    unitD{"4I", "METERS PER SECOND", precise::m / precise::s},
    unitD{"4J", "METERS PER SECOND PER SECOND", precise::m / precise::s.pow(2)},
    unitD{"4S", "PASCAL", precise::Pa},
    unitD{"4V", "CUBIC METER PER HOUR", precise::m.pow(3) / precise::hr},
    unitD{"51", "ACTUAL TONNES", {1.0, ton, commodities::packaging::actual}},
    unitD{"57", "MESH", clinical::mesh},
    unitD{"58", "NET KILOGRAMS", kg},
    unitD{"5B", "BATCH", {1.0, count, commodities::packaging::batch}},
    unitD{"5D", "PROOF GALLONS", precise::one},
    unitD{"5G", "PUMP", {1.0, count, commodities::packaging::pump}},
    unitD{"5H", "STAGE", {1.0, count, commodities::packaging::stage}},
    unitD{"5I", "STANDARD CUBE FOOT", ft.pow(3)},
    unitD{"65", "COULOMB", precise::C},
    unitD{"67", "SIEMENS", precise::S},
    unitD{"68", "AMPERE", precise::A},
    unitD{"7A", "LANDINGS", count},
    unitD{"7C", "FLIGHT HOURS", h},
    unitD{"82", "OHM", precise::ohm},
    unitD{"83", "FARAD", precise::F},
    unitD{"86", "JOULES", precise::J},
    unitD{"8C", "CORD", precise::us::cord},
    unitD{"8D", "DUTY", precise::one},
    unitD{"8P", "PROJECT", precise::one},
    unitD{"8R", "PROGRAM", precise::one},
    unitD{"8S", "SESSION", precise::one},
    unitD{"91", "STOKE", cgs::stokes},
    unitD{"94", "CURL UNIT", precise::one},
    unitD{"95", "20,000 GALLON TANKCAR", precise::one},
    unitD{"96", "10,000 GALLON TANKCAR", precise::one},
    unitD{"97", "10 KILOGRAM DRUM", {10.0, kg, commodities::packaging::drum}},
    unitD{"98", "15 KILOGRAM DRUM", precise::one},
    unitD{"9Y", "FAMILY UNIT", precise::one},
    unitD{"AB", "BULK PACK", precise::one},
    unitD{"AC", "ACRE", precise::acre},
    unitD{"AD", "APOTHECARY DRAM", data::byte},
    unitD{"AJ", "COP (CYLINDRICAL OR CONICAL MASS)", precise::one},
    unitD{"AL", "ACCESS LINES", precise::one},
    unitD{"AM", "AMPOULE", precise::one},
    unitD{"AO", "APOTHECARY OUNCE", apothecaries::ounce},
    unitD{"AP", "APOTHECARY POUND", {1.0, lb, commodities::aluminum}},
    unitD{"AR", "SUPPOSITORY", precise::one},
    unitD{"AS", "APOTHECARY SCRUPLE", apothecaries::scruple},
    unitD{"AT", "ATMOSPHERE", pressure::atm},
    unitD{"AV", "CAPSULE", precise::one},
    unitD{"AW", "POWDER-FILLED VIAL", precise::one},
    unitD{"AX", "TWENTY", precise::one},
    unitD{"AY", "ASSEMBLY", precise::one},
    unitD{"B0", "BRITISH THERMAL UNITS PER CUBIC FOOT", precise::one},
    unitD{"B1", "BARREL, LIQUID", us::barrel / day},
    unitD{"B2", "BARREL, DRY", {1.0, count, commodities::packaging::bunk}},
    unitD{"B3", "BATTING POUND", precise::one},
    unitD{"B4", "BARREL IMPERIAL", precise::one},
    unitD{"B5", "BILLET", precise::one},
    unitD{"B6", "BUN", precise::one},
    unitD{"B7", "CYCLE", precise::one},
    unitD{"B8", "BOARD", precise::one},
    unitD{"B9", "BATT", precise::one},
    unitD{"BA", "BALL", {1.0, count, commodities::packaging::bale}},
    unitD{"BB", "BASS BOX", precise::one},
    unitD{"BC", "BUCKET", precise::one},
    unitD{"BD", "BUNDLE", precise::one},
    unitD{"BE", "BALE", {1.0, count, commodities::packaging::beam}},
    unitD{"BF", "BOARD FOOT", precise::one},
    unitD{"BG", "BAG", precise::one},
    unitD{"BH", "BRUSH", precise::one},
    unitD{"BI", "BELT", precise::one},
    unitD{"BJ", "BAND", precise::one},
    unitD{"BK", "BOOK", precise::one},
    unitD{"BL", "BARREL", {1.0, count, commodities::packaging::block}},
    unitD{"BM", "BEAM", {1.0, count, commodities::packaging::bolt}},
    unitD{"BN", "BULK", precise::one},
    unitD{"BO", "BOLT", {1.0, count, commodities::packaging::bottle}},
    unitD{"BP", "100 BOARD FEET", precise::one},
    unitD{"BQ", "BRIQUET", power::hpM},
    unitD{"BR", "BAR", us::barrel},
    unitD{"BS", "BASKET", precise::one},
    unitD{"BT", "BOTTLE", {1.0, count, commodities::packaging::belt}},
    unitD{"BU", "BUSHEL (32 DRY QUARTS)", precise::one},
    unitD{"BV", "BUSHEL DRY IMPERIAL", precise::one},
    unitD{"BW", "BASE WEIGHT", precise::one},
    unitD{"BX", "BOX", precise::one},
    unitD{"BY", "BUNK", precise::one},
    unitD{"BZ", "BLOCK", mega* btu},
    unitD{"C0", "CALLS", precise::one},
    unitD{"C1", "COMPOSITE PRODUCT POUNDS (TOTAL WEIGHT)", precise::one},
    unitD{"C2", "SQUARE CENTIMETER", {1.0, count, commodities::packaging::carset}},
    unitD{"C3", "COMBO", centi* L},
    unitD{"C4", "CARLOAD", precise::one},
    unitD{"C5", "COST", {1.0, currency, commodities::packaging::actual}},
    unitD{"C6", "CELL", precise::one},
    unitD{"C7", "CARSET", centi* cgs::poise},
    unitD{"C8", "CUBIC DECIMETER", precise::one},
    unitD{"C9", "COIL GROUP", precise::one},
    unitD{"CA", "CARTRIDGE", {1.0, count, commodities::packaging::small_case}},
    unitD{"CB", "CARBOY", precise::one},
    unitD{"CC", "CUBIC CENTIMETER", cm.pow(3)},
    unitD{"CD", "CUBIC YARD", precise::one},
    unitD{"CE", "CONE", degC},
    unitD{"CF", "CUBIC FOOT", ft.pow(3)},
    unitD{"CG", "CENTIGRAM", {1.0, count, commodities::packaging::card}},
    unitD{"CH", "CHAIN", precise::one},
    unitD{"CI", "CUBIC INCH", in.pow(3)},
    unitD{"CK", "CAKE", precise::one},
    unitD{"CL", "COIL", {1.0, count, commodities::packaging::cylinder}},
    unitD{"CM", "CENTIMETER", cm},
    unitD{"CN", "CAN", precise::one},
    unitD{"CO", "CONTAINER", m.pow(3)},
    unitD{"CP", "CRATE", precise::one},
    unitD{"CQ", "CARD", precise::one},
    unitD{"CR", "CONNECTOR", m.pow(3)},
    unitD{"CS", "CASE", precise::one},
    unitD{"CT", "CARTON", precise::one},
    unitD{"CU", "CUP", precise::one},
    unitD{"CV", "COVER", precise::one},
    unitD{"CW", "HUNDRED WEIGHT (LONG)", precise::one},
    unitD{"CX", "CASSETTE", precise::one},
    unitD{"CY", "CYLINDER", precise::one},
    unitD{"CZ", "CUBIC METER", precise::one},
    unitD{"DA", "DAY", precise::one},
    unitD{"DB", "DECIBEL", precise::one},
    unitD{"DC", "DECAGRAM", precise::one},
    unitD{"DE", "DECIMETER", precise::one},
    unitD{"DF", "FAHRENHEIT", precise::one},
    unitD{"DG", "DECIGRAM", precise::one},
    unitD{"DI", "DISPENSER", precise::one},
    unitD{"DK", "DEGREES, KELVIN", precise::one},
    unitD{"DL", "DECILITER", precise::one},
    unitD{"DM", "DRAM", precise::one},
    unitD{"DO", "DOLLARS U.S.", precise::one},
    unitD{"DP", "DOZEN PAIR", precise::one},
    unitD{"DQ", "DATA RECORD", precise::one},
    unitD{"DR", "DRUM", precise::one},
    unitD{"DS", "DISPLAY", precise::one},
    unitD{"DT", "DRY TON", precise::one},
    unitD{"DU", "DYNE", cgs::dyn},
    unitD{"DW", "PENNYWEIGHT", precise::one},
    unitD{"DX", "CALENDAR DAYS (NUMBER OF)", precise::one},
    unitD{"DY", "DIRECTORY BOOKS", precise::one},
    unitD{"DZ", "DOZEN", {12, count}},
    unitD{"E1", "HECTOMETER", precise::one},
    unitD{"EA", "EACH", one},
    unitD{"EB", "ELECTRONIC MAIL BOXES", precise::one},
    unitD{"EE", "EMPLOYEES", precise::one},
    unitD{"EH", "KNOTS", precise::one},
    unitD{"EJ", "LOCATIONS", precise::one},
    unitD{"EP", "ELEVEN PACK", {11, one}},
    unitD{"EQ", "EQUIVALENT GALLONS", precise::one},
    unitD{"EV", "ENVELOPES", precise::one},
    unitD{"F4", "MINIM", precise::one},
    unitD{"F6", "PRICE PER SHARE", precise::one},
    unitD{"FA", "FATHOM", precise::one},
    unitD{"FB", "FIELDS", precise::one},
    unitD{"FC", "1000 CUBIC FEET", precise::one},
    unitD{"FD", "FOLD", precise::one},
    unitD{"FE", "TRACK FOOT", precise::one},
    unitD{"FF", "HUNDRED CUBIC METERS", precise::one},
    unitD{"FG", "TRANSDERMAL PATCH", precise::one},
    unitD{"FJ", "SIZING FACTOR", precise::one},
    unitD{"FK", "FIBER", precise::one},
    unitD{"FL", "FLAKE TON", precise::one},
    unitD{"FM", "MILLION CUBIC FEET", precise::one},
    unitD{"FO", "FLUID OUNCE", precise::one},
    unitD{"FR", "FRAME", precise::one},
    unitD{"FT", "FOOT", precise::one},
    unitD{"FU", "FURLONG", precise::one},
    unitD{"FV", "FIVE", precise::one},
    unitD{"FY", "FIFTY", precise::one},
    unitD{"GB", "GALLONS PER MINUTE", precise::one},
    unitD{"GG", "GREAT GROSS", precise::one},
    unitD{"GI", "GILL (IMPERIAL)", precise::one},
    unitD{"GL", "GALLON", precise::one},
    unitD{"GM", "GRAM", precise::one},
    unitD{"GN", "GRAIN", precise::one},
    unitD{"GP", "GROUP", precise::one},
    unitD{"GR", "GROSS", precise::one},
    unitD{"GT", "THOUSAND GALLONS PER DAY", precise::one},
    unitD{"GX", "APOTHECARY GRAIN", precise::one},
    unitD{"H2", "HALF LITER", precise::one},
    unitD{"H4", "HECTOLITER", precise::one},
    unitD{"HA", "HUNDRED CUBIC FEET", precise::one},
    unitD{"HB", "HOSPITAL BEDS", precise::one},
    unitD{"HC", "HUNDRED COUNT", precise::one},
    unitD{"HD", "HUNDRED", precise::one},
    unitD{"HF", "HUNDRED FEET", precise::one},
    unitD{"HG", "HECTOGRAM", precise::one},
    unitD{"HH", "HOGSHEAD", precise::one},
    unitD{"HI", "HUNDRED SHEETS", precise::one},
    unitD{"HK", "HANK", precise::one},
    unitD{"HL", "HUNDRED FEET (LINEAR)", precise::one},
    unitD{"HO", "HUNDRED TROY OUNCES", precise::one},
    unitD{"HP", "HUNDRED POUNDS", precise::one},
    unitD{"HQ", "HECTARE", precise::one},
    unitD{"HR", "HOUR", precise::one},
    unitD{"HS", "HUNDRED SQUARE FEET", precise::one},
    unitD{"HT", "HALF HOUR", precise::one},
    unitD{"HW", "HUNDRED WEIGHT - SHORT (HUNDRED WEIGHT)", precise::one},
    unitD{"HX", "HUNDRED BOXES", precise::one},
    unitD{"HY", "HUNDRED YARDS", precise::one},
    unitD{"HZ", "HALF DOZEN", precise::one},
    unitD{"I1", "PERSONS, CAPACITY", precise::one},
    unitD{"IG", "IMPERIAL GALLON", precise::one},
    unitD{"IH", "INHALER", precise::one},
    unitD{"IM", "IMPRESSION", precise::one},
    unitD{"IN", "INCH", precise::one},
    unitD{"IP", "INSURANCE POLICY", precise::one},
    unitD{"IS", "STOP", precise::one},
    unitD{"IU", "INTERNATIONAL UNIT", precise::one},
    unitD{"JB", "JOB", precise::one},
    unitD{"JG", "JUG", precise::one},
    unitD{"JO", "JOINT", precise::one},
    unitD{"JR", "JAR", precise::one},
    unitD{"JU", "JUMBO", precise::one},
    unitD{"K2", "SQUARE KILOMETER", precise::one},
    unitD{"K6", "KILOLITER", precise::one},
    unitD{"K7", "KILOWATT", precise::one},
    unitD{"KC", "KILOCURIE", precise::one},
    unitD{"KE", "KEG", precise::one},
    unitD{"KF", "KILOPACKET", precise::one},
    unitD{"KG", "KILOGRAM", precise::one},
    unitD{"KH", "HUNDREDS OF KILOGRAMS", precise::one},
    unitD{"KK", "100 KILOGRAMS", precise::one},
    unitD{"KM", "KILOMETER", precise::km},
    unitD{"KR", "KARAT (CARAT)", precise::one},
    unitD{"KT", "KIT", precise::one},
    unitD{"KU", "TASK", precise::one},
    unitD{"KV", "KILOVOLT", precise::electrical::kV},
    unitD{"KZ", "KILOWATT-HOUR", precise::kWh},
    unitD{"L5", "LITERS AT 15 DEGREES CELSIUS", precise::one},
    unitD{"LB", "POUND (AVOIRDUPOIS)", precise::one},
    unitD{"LE", "LITE", precise::one},
    unitD{"LF", "LINEAR FOOT", precise::one},
    unitD{"LG", "LENGTH", precise::one},
    unitD{"LI", "LITER", precise::one},
    unitD{"LJ", "LARGE SPRAY", precise::one},
    unitD{"LK", "LINK", precise::one},
    unitD{"LM", "LINEAR METER", precise::one},
    unitD{"LN", "LINEAR INCH", precise::one},
    unitD{"LO", "LONG TON", precise::one},
    unitD{"LR", "LAYER", precise::one},
    unitD{"LS", "LUMP SUM", precise::one},
    unitD{"LT", "LOT", precise::one},
    unitD{"LY", "LINEAR YARD", precise::one},
    unitD{"M0", "MAGNETIC TAPE", precise::one},
    unitD{"M2", "SQUARE MILE", precise::one},
    unitD{"M3", "MAT", precise::one},
    unitD{"M5", "MICROGRAM", precise::one},
    unitD{"M6", "METRIC TON", precise::one},
    unitD{"MA", "METRIC NET TON", precise::one},
    unitD{"MB", "BRITISH THERMAL UNITS/HOUR", precise::btu / precise::hr},
    unitD{"MC", "THOUSAND CUBIC FEET", precise::one},
    unitD{"MD", "AIR DRY METRIC TON", precise::one},
    unitD{"ME", "MEAL", precise::one},
    unitD{"MF", "THOUSAND FEET", precise::one},
    unitD{"MG", "MILLIGRAM", precise::mg},
    unitD{"MH", "METRIC", precise::one},
    unitD{"MI", "MILE", precise::one},
    unitD{"MJ", "METRIC GROSS TON", precise::one},
    unitD{"MK", "METRIC LONG TON", precise::one},
    unitD{"ML", "MILLILITER", precise::one},
    unitD{"MM", "MILLIMETER", precise::mm},
    unitD{"MO", "MONTH", precise::one},
    unitD{"MQ", "1000 METERS", precise::one},
    unitD{"MR", "METER", precise::one},
    unitD{"MS", "SQUARE MILLIMETER", precise::one},
    unitD{"MT", "MINUTE", precise::one},
    unitD{"MX", "THOUSAND", precise::one},
    unitD{"MZ", "MIXED", precise::one},
    unitD{"N2", "NUMBER OF LINES", precise::one},
    unitD{"N7", "PART", precise::one},
    unitD{"N9", "CARTRIDGE NEEDLE", precise::one},
    unitD{"NB", "BARGE", precise::one},
    unitD{"NC", "CAR", precise::one},
    unitD{"ND", "NET BARRELS", precise::one},
    unitD{"NE", "NET LITERS", precise::one},
    unitD{"NF", "MESSAGES", precise::one},
    unitD{"NG", "NET GALLONS", precise::one},
    unitD{"NI", "NET IMPERIAL GALLONS", precise::one},
    unitD{"NJ", "NUMBER OF SCREENS", precise::one},
    unitD{"NK", "NIGHTS", precise::one},
    unitD{"NL", "LOAD", precise::one},
    unitD{"NM", "NAUTICAL MILE", precise::one},
    unitD{"NN", "TRAIN", precise::one},
    unitD{"NS", "SHORT TON", precise::one},
    unitD{"NT", "TRAILER", precise::one},
    unitD{"NV", "VEHICLE", precise::one},
    unitD{"NX", "PARTS PER THOUSAND", precise::one},
    unitD{"OA", "PANEL", precise::one},
    unitD{"OC", "BILLBOARD", precise::one},
    unitD{"OL", "OUTLET", precise::one},
    unitD{"OP", "TWO PACK", precise::one},
    unitD{"OT", "OUTFIT", precise::one},
    unitD{"OU", "OPERATING UNIT", precise::one},
    unitD{"OZ", "OUNCE - AV", precise::one},
    unitD{"P0", "PAGE - ELECTRONIC", precise::one},
    unitD{"P1", "PERCENT", precise::one},
    unitD{"P2", "POUNDS PER FOOT", precise::one},
    unitD{"P3", "THREE PACK", precise::one},
    unitD{"P4", "FOUR PACK", precise::one},
    unitD{"P5", "FIVE PACK", precise::one},
    unitD{"P6", "SIX PACK", precise::one},
    unitD{"P7", "SEVEN PACK", precise::one},
    unitD{"P8", "EIGHT PACK", precise::one},
    unitD{"P9", "NINE PACK", precise::one},
    unitD{"PA", "PAGE", precise::one},
    unitD{"PB", "PAIR INCHES", precise::one},
    unitD{"PC", "PIECE", precise::one},
    unitD{"PD", "PAD", precise::one},
    unitD{"PE", "POUNDS EQUIVALENT", precise::one},
    unitD{"PF", "PALLET (LIFT)", precise::one},
    unitD{"PG", "PACKAGE", precise::one},
    unitD{"PH", "PACK (PAK)", precise::one},
    unitD{"PI", "PILLOW", precise::one},
    unitD{"PJ", "PALLET/UNIT LOAD", precise::one},
    unitD{"PK", "PECK DRY US", precise::one},
    unitD{"PL", "PAIL", precise::one},
    unitD{"PM", "PLATE", precise::one},
    unitD{"PN", "PERSON", precise::one},
    unitD{"PO", "POUNDS GROSS", precise::one},
    unitD{"PP", "PINT IMPERIAL", precise::one},
    unitD{"PQ", "PECK DRY IMPERIAL", precise::one},
    unitD{"PR", "PAIR", precise::one},
    unitD{"PS", "POUNDS NET", precise::one},
    unitD{"PT", "PINT", precise::one},
    unitD{"PU", "MASS POUNDS", precise::one},
    unitD{"PV", "HALF PINT", precise::one},
    unitD{"PX", "PELLET", precise::one},
    unitD{"PY", "PITCH", precise::one},
    unitD{"PZ", "PACKET", precise::one},
    unitD{"QC", "CHANNEL", precise::one},
    unitD{"QE", "PHOTOGRAPHS", precise::one},
    unitD{"QF", "QUARTER", precise::one},
    unitD{"QI", "QUART IMPERIAL", precise::one},
    unitD{"QK", "QUARTER KILOGRAM", precise::one},
    unitD{"QR", "QUIRE", precise::one},
    unitD{"QS", "QUART DRY U.S.", precise::one},
    unitD{"QT", "QUART", precise::one},
    unitD{"QU", "QUARTER DOZEN", precise::one},
    unitD{"R4", "CALORIE", precise::one},
    unitD{"R5", "THOUSANDS OF DOLLARS", precise::one},
    unitD{"R9", "THOUSAND CUBIC METERS", precise::one},
    unitD{"RA", "RATION", precise::one},
    unitD{"RB", "RADIAN", precise::one},
    unitD{"RC", "ROD (AREA) - 16.25 SQUARE YARDS", precise::one},
    unitD{"RD", "ROD (LENGTH) - 5.5 YARDS", precise::one},
    unitD{"RE", "ROUND", precise::one},
    unitD{"RG", "RING", precise::one},
    unitD{"RH", "RUNNING OR OPERATING HOURS", precise::one},
    unitD{"RK", "ROLL-METRIC MEASURE", precise::one},
    unitD{"RL", "REEL", precise::one},
    unitD{"RM", "REAM", precise::one},
    unitD{"RN", "REAM-METRIC MEASURE", precise::one},
    unitD{"RO", "ROLL", precise::one},
    unitD{"RP", "POUNDS PER REAM", precise::one},
    unitD{"RR", "RACK", precise::one},
    unitD{"RS", "RESETS", precise::one},
    unitD{"RT", "REVENUE TON MILES", precise::one},
    unitD{"RU", "RUN", precise::one},
    unitD{"RX", "THOUSAND ROUNDS", precise::one},
    unitD{"S5", "SIXTY-FOURTHS OF AN INCH", precise::one},
    unitD{"S6", "SESSIONS", precise::one},
    unitD{"S7", "STORAGE UNITS", precise::one},
    unitD{"S8", "SHELF PACKAGE", precise::one},
    unitD{"S9", "SLIP SHEET", precise::one},
    unitD{"SA", "SANDWICH", precise::one},
    unitD{"SB", "SHIPMENT", precise::one},
    unitD{"SC", "SECOND", precise::one},
    unitD{"SD", "SKID", precise::one},
    unitD{"SE", "SET", precise::one},
    unitD{"SF", "SQUARE FOOT", precise::one},
    unitD{"SG", "SEGMENT", precise::one},
    unitD{"SH", "SHEET", precise::one},
    unitD{"SI", "SQUARE INCH", precise::one},
    unitD{"SJ", "SACK", precise::one},
    unitD{"SK", "SKEIN", precise::one},
    unitD{"SL", "SPOOL", precise::one},
    unitD{"SM", "SQUARE METER", precise::one},
    unitD{"SN", "SECTION (640 ACRES OR ONE SQUARE MILE)", precise::one},
    unitD{"SO", "SHOT", precise::one},
    unitD{"SP", "STRIP", precise::one},
    unitD{"SQ", "SQUARE", precise::one},
    unitD{"SR", "SPLIT TANKTRUCK", precise::one},
    unitD{"SS", "SHEET-METRIC MEASURE", precise::one},
    unitD{"ST", "SEAT", precise::one},
    unitD{"SU", "SQUARE ROD", precise::one},
    unitD{"SV", "SLEEVE", precise::one},
    unitD{"SW", "STANDARD ADVERTISING UNIT", precise::one},
    unitD{"SX", "STICK", precise::one},
    unitD{"SY", "SQUARE YARD", precise::yd.pow(2)},
    unitD{"SZ", "SYRINGE", precise::one},
    unitD{"T1", "THOUSAND POUNDS GROSS", precise::one},
    unitD{"T2", "TEASPOON", precise::us::tsp},
    unitD{"T3", "THOUSAND PIECES", precise::one},
    unitD{"T4", "THOUSAND BAGS", precise::one},
    unitD{"T5", "THOUSAND CASINGS", precise::one},
    unitD{"T6", "THOUSAND GALLONS", precise::one},
    unitD{"T7", "THOUSAND IMPRESSIONS", precise::one},
    unitD{"T8", "THOUSAND LINEAR INCHES", precise::one},
    unitD{"T9", "THOUSAND KILOWATT HOURS/MEGAWATT-HOUR", precise::one},
    unitD{"TA", "TENTH CUBIC FOOT", precise::one},
    unitD{"TB", "TABLESPOON", precise::one},
    unitD{"TC", "TRUCK LOAD", precise::one},
    unitD{"TD", "therm", energy::therm_ec},
    unitD{"TE", "TEN", precise::ten},
    unitD{"TF", "TWENTY-FIVE", precise_unit(25.0, precise::one)},
    unitD{"TG", "GROSS TON", precise::one},
    unitD{"TH", "THOUSAND KILOGRAMS", precise::kilo* precise::kilogram},
    unitD{"TI", "THOUSAND SQUARE INCHES", precise::one},
    unitD{"TJ", "THOUSAND SQUARE CENTIMETERS", precise::one},
    unitD{"TK", "TANK", precise::one},
    unitD{"TL", "THOUSAND LINEAR METERS", precise::one},
    unitD{"TM", "THOUSAND FEET (BOARD)", precise::one},
    unitD{"TN", "NET TON (2,000 POUNDS)", precise::one},
    unitD{"TO", "TROY OUNCE", precise::troy::oz},
    unitD{"TP", "TROY POUND", precise::troy::pound},
    unitD{"TQ", "THOUSAND FEET", precise::one},
    unitD{"TR", "TEN SQUARE FEET", precise::one},
    unitD{"TS", "THIRTY-SIX", precise::one},
    unitD{"TT", "TABLET", precise::one},
    unitD{"TU", "TUBE", precise::one},
    unitD{"TV", "TEN-PACK", precise::one},
    unitD{"TW", "THOUSAND SHEETS", precise::one},
    unitD{"TX", "THOUSAND LINEAR YARDS", precise::one},
    unitD{"TY", "TRAY", precise::one},
    unitD{"TZ", "THOUSAND SQUARE FEET", precise::one},
    unitD{"U1", "TREATMENT", precise::one},
    unitD{"U5", "TWO HUNDRED FIFTY", precise::one},
    unitD{"U6", "UNITED STATES GALLONS @ 60 DEGREES FAHRENHEIT", precise::one},
    unitD{"UH", "TEN THOUSAND YARDS", precise_unit(10000.0, precise::yd)},
    unitD{"UL", "UNITLESS", precise::one},
    unitD{"UM", "MILLION UNITS", precise::one},
    unitD{"UN", "UNIT", precise::one},
    unitD{"UP", "TROCHE", precise::one},
    unitD{"UQ", "WAFER", precise::one},
    unitD{"US", "USP UNIT", precise::one},
    unitD{"V1", "FLAT", precise::one},
    unitD{"V2", "POUCH", precise::one},
    unitD{"VA", "volt - ampere per kilogram", V* A / kg},
    unitD{"VC", "FIVE HUNDRED", precise::one},
    unitD{"VI", "VIAL", precise::one},
    unitD{"VS", "VISIT", precise::one},
    unitD{"VT", "VOLT", precise::one},
    unitD{"W2", "WET KILO", precise::one},
    unitD{"WA", "watt per kilogram", W / kg},
    unitD{"WB", "WET POUND", precise::one},
    unitD{"WD", "WORK DAY", precise::one},
    unitD{"WE", "WET TON", precise::one},
    unitD{"WG", "WINE GALLON", precise::one},
    unitD{"WH", "WHEEL", precise::one},
    unitD{"WK", "WEEK", precise::one},
    unitD{"WR", "WRAP", precise::one},
    unitD{"WT", "WATT", precise::one},
    unitD{"X2", "BUNCH", precise::one},
    unitD{"X3", "CLOVE", precise::one},
    unitD{"X4", "DROP", precise::one},
    unitD{"X5", "HEAD", precise::one},
    unitD{"X6", "HEART", precise::one},
    unitD{"X7", "LEAF", precise::one},
    unitD{"X8", "LOAF", precise::one},
    unitD{"X9", "PORTION", precise::one},
    unitD{"Y1", "SLICE", precise::one},
    unitD{"Y4", "TUB", precise::one},
    unitD{"YD", "YARD", precise::yd},
    unitD{"YL", "100 LINEAL YARDS", precise::one},
    unitD{"YR", "YEAR", precise::yr},
    unitD{"YT", "BYTE", precise::data::byte},
    unitD{"Z1", "LIFT VAN", precise::one},
    unitD{"Z2", "CHEST", precise::one},
    unitD{"Z3", "CASK", precise::one},
    unitD{"Z5", "LUG", precise::one},
    unitD{
        "ZF",
        "MILLION BTUS/DEKATHERM",
        precise::mega* precise::btu /
            precise_unit(10.0, precise::energy::therm_ec)},
}};

}  // namespace precise

precise_unit x12_unit(const std::string& x12_string)
{
    // NOLINTNEXTLINE (readability-qualified-auto)
    auto ind = std::lower_bound(
        precise::x12_units.begin(),
        precise::x12_units.end(),
        x12_string,
        [](const precise::unitD& u_set, const std::string& val) {
            return (strcmp(std::get<0>(u_set), val.c_str()) < 0);
        });
    if (ind == precise::x12_units.end()) {
        return precise::invalid;
    }
    if (strcmp(std::get<0>(*ind), x12_string.c_str()) == 0) {
        return std::get<2>(*ind);
    }
    return precise::invalid;
}

precise_unit dod_unit(const std::string& dod_string)
{
    // NOLINTNEXTLINE (readability-qualified-auto)
    auto ind = std::lower_bound(
        precise::dod_units.begin(),
        precise::dod_units.end(),
        dod_string,
        [](const precise::unitD& u_set, const std::string& val) {
            return (strcmp(std::get<0>(u_set), val.c_str()) < 0);
        });
    if (ind == precise::dod_units.end()) {
        return precise::invalid;
    }
    if (strcmp(std::get<0>(*ind), dod_string.c_str()) == 0) {
        return std::get<2>(*ind);
    }
    return precise::invalid;
}



#ifdef ENABLE_UNIT_MAP_ACCESS
namespace detail {
    const void* x12rawData(size_t& array_size)
    {
        array_size = precise::x12_units.size();
        return precise::x12_units.data();
    }
    const void* dodrawData(size_t& array_size)
    {
        array_size = precise::dod_units.size();
        return precise::dod_units.data();
    }
}  // namespace detail

#endif

}  // namespace UNITS_NAMESPACE