name: Static Analyzers

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cpplint:
    runs-on: ubuntu-latest
    container: helics/buildenv:cpplint

    steps:
    - uses: actions/checkout@v2
    - name: Run cpplint
      run: cpplint --counting=detailed --recursive units test webserver converter  
  cppcheck:
    runs-on: ubuntu-latest
    container: helics/buildenv:cppcheck2

    steps:
    - uses: actions/checkout@v2
    - name: Run cppcheck
      run: cppcheck --enable=performance,portability,unusedFunction -UEXTRA_UNIT_STANDARDS --error-exitcode=-4 -i ThirdParty -i FuzzTargets -i docs -i config .